// ── SQUADS MANQUANTS (injectés via initMissingTeams() appelé depuis main.js) ──
const MISSING_TEAMS = {

  'Rép. tchèque': {
    flag:'🇨🇿', color:'#d7141a', coach:'Ivan Hašek', formation:'4-2-3-1',
    confederation:'UEFA', bannerImg:'', rating:78,
    posterImg:'images/poster_czech.png',
    players:[
      // ─── GARDIENS ────────────────────────────
      { id: 'cz12', name: 'Matěj KOVÁŘ', pos: 'Gardien', n: 0, age: 26, born: 'May 17, 2000', club: 'PSV Eindhoven', caps: 19, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: 'Doublure fiable, excellent avec les pieds.' },
      { id: 'cz1', name: 'Jiří STANĚK', pos: 'Gardien', n: 0, age: 30, born: 'April 27, 1996', club: 'Slavia Prague', caps: 14, goals: 0, ast: 0, photo: 'https://img.sofascore.com/api/v1/player/280601/image', role: 'Remplaçant', bio: 'Gardien numéro 1, réflexes exceptionnels.' },
      { id: 'cz0', name: 'Lukáš HORNÍČEK', pos: 'Gardien', n: 0, age: 23, born: 'July 13, 2002', club: 'Braga', caps: 0, goals: 0, ast: 0, photo: '', role: 'Remplaçant', bio: '' },
      // ─── DÉFENSEURS ────────────────────────────
      { id: 'cz2', name: 'Vladimír COUFAL', pos: 'Défenseur', n: 0, age: 33, born: 'August 22, 1992', club: 'TSG Hoffenheim', caps: 61, goals: 2, ast: 0, photo: 'https://img.sofascore.com/api/v1/player/138024/image', role: 'Titulaire', bio: 'Latéral droit combatif, régulier en Premier League.' },
      { id: 'cz3', name: 'Tomáš HOLEŠ', pos: 'Défenseur', n: 0, age: 33, born: 'March 31, 1993', club: 'Slavia Prague', caps: 39, goals: 2, ast: 0, photo: 'https://img.sofascore.com/api/v1/player/151440/image', role: 'Titulaire', bio: 'Défenseur central polyvalent et agressif.' },
      { id: 'cz0', name: 'Ladislav KREJČÍ', pos: 'Défenseur', n: 0, age: 27, born: 'April 20, 1999', club: 'Wolverhampton Wanderers', caps: 25, goals: 5, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'David ZIMA', pos: 'Défenseur', n: 0, age: 25, born: 'November 8, 2000', club: 'Slavia Prague', caps: 24, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Jaroslav ZELENÝ', pos: 'Défenseur', n: 0, age: 33, born: 'August 20, 1992', club: 'Sparta Prague', caps: 21, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz5', name: 'David JURÁSEK', pos: 'Défenseur', n: 0, age: 25, born: 'August 7, 2000', club: 'Slavia Prague', caps: 16, goals: 1, ast: 0, photo: 'https://img.sofascore.com/api/v1/player/1030711/image', role: 'Titulaire', bio: 'Latéral gauche technique, explosif offensivement.' },
      { id: 'cz0', name: 'David DOUDĚRA', pos: 'Défenseur', n: 0, age: 28, born: 'May 31, 1998', club: 'Slavia Prague', caps: 15, goals: 2, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Robin HRANÁČ', pos: 'Défenseur', n: 0, age: 26, born: 'January 29, 2000', club: 'TSG Hoffenheim', caps: 12, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Štěpán CHALOUPEK', pos: 'Défenseur', n: 0, age: 23, born: 'March 8, 2003', club: 'Slavia Prague', caps: 3, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      // ─── MILIEUX ────────────────────────────
      { id: 'cz6', name: 'Tomáš SOUČEK', pos: 'Milieu', n: 0, age: 31, born: 'February 27, 1995', club: 'West Ham United', caps: 89, goals: 17, ast: 0, photo: 'https://img.sofascore.com/api/v1/player/799041/image', role: 'Titulaire', bio: 'Box-to-box, force physique et but crucial.' },
      { id: 'cz0', name: 'Vladimír DARIDA', pos: 'Milieu', n: 0, age: 35, born: 'August 8, 1990', club: 'Hradec Králové', caps: 78, goals: 8, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz7', name: 'Lukáš PROVOD', pos: 'Milieu', n: 0, age: 29, born: 'October 23, 1996', club: 'Slavia Prague', caps: 37, goals: 3, ast: 0, photo: 'https://img.sofascore.com/api/v1/player/846122/image', role: 'Titulaire', bio: 'Milieu dynamique, redoutable dans la transition.' },
      { id: 'cz18', name: 'Michal SADÍLEK', pos: 'Milieu', n: 0, age: 27, born: 'May 31, 1999', club: 'Slavia Prague', caps: 33, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: 'Milieu central élégant, bon relayeur.' },
      { id: 'cz0', name: 'Pavel ŠULC', pos: 'Milieu', n: 0, age: 25, born: 'December 29, 2000', club: 'Lyon', caps: 20, goals: 5, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Lukáš ČERV', pos: 'Milieu', n: 0, age: 25, born: 'April 10, 2001', club: 'Viktoria Plzeň', caps: 15, goals: 2, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Tomáš LADRA', pos: 'Milieu', n: 0, age: 29, born: 'May 24, 1997', club: 'Viktoria Plzeň', caps: 1, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Pavel BUCHA', pos: 'Milieu', n: 0, age: 28, born: 'March 11, 1998', club: 'FC Cincinnati', caps: 0, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Hugo SOCHŮREK', pos: 'Milieu', n: 0, age: 18, born: 'June 7, 2008', club: 'Sparta Prague', caps: 0, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Alexandr SOJKA', pos: 'Milieu', n: 0, age: 23, born: 'April 2, 2003', club: 'Viktoria Plzeň', caps: 0, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Denis VIŠINSKÝ', pos: 'Milieu', n: 0, age: 23, born: 'March 21, 2003', club: 'Viktoria Plzeň', caps: 0, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      // ─── ATTAQUANTS ────────────────────────────
      { id: 'cz9', name: 'Patrik SCHICK', pos: 'Attaquant', n: 0, age: 30, born: 'January 24, 1996', club: 'Bayer Leverkusen', caps: 52, goals: 25, ast: 0, photo: 'https://img.sofascore.com/api/v1/player/280609/image', role: 'Titulaire', bio: 'Attaquant de classe mondiale, buteur redoutable.' },
      { id: 'cz10', name: 'Adam HLOŽEK', pos: 'Attaquant', n: 0, age: 23, born: 'July 25, 2002', club: 'TSG Hoffenheim', caps: 41, goals: 4, ast: 0, photo: 'https://img.sofascore.com/api/v1/player/963801/image', role: 'Titulaire', bio: 'Ailier technique, montée en puissance spectaculaire.' },
      { id: 'cz19', name: 'Jan KUCHTA', pos: 'Attaquant', n: 0, age: 29, born: 'January 8, 1997', club: 'Sparta Prague', caps: 30, goals: 3, ast: 0, photo: '', role: 'Titulaire', bio: 'Avant-centre combatif, pression haute efficace.' },
      { id: 'cz0', name: 'Tomáš CHORÝ', pos: 'Attaquant', n: 0, age: 31, born: 'January 26, 1995', club: 'Slavia Prague', caps: 21, goals: 6, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Mojmír CHYTIL', pos: 'Attaquant', n: 0, age: 27, born: 'April 29, 1999', club: 'Slavia Prague', caps: 21, goals: 6, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'cz0', name: 'Christophe KABONGO', pos: 'Attaquant', n: 0, age: 22, born: 'August 27, 2003', club: 'Mladá Boleslav', caps: 0, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
    ]
  },

  'Bosnie-Herzégovine': {
    flag:'🇧🇦', color:'#002395', coach:'Sergej Barbarez', formation:'4-2-3-1',
    confederation:'UEFA', bannerImg:'', rating:74,
    posterImg:'images/poster_bosnia.png',
    players:[
      {id:'bih1',  name:'Nikola VASILJ',      pos:'Gardien',   n:1,  age:28, born:'06/03/1996', h:'1m90', club:'St. Pauli',         caps:18, goals:0, ast:0, debut:'2021', photo:'https://img.sofascore.com/api/v1/player/325061/image', role:'Titulaire',  bio:'Gardien solide, excellente réactivité.'},
      {id:'bih2',  name:'Sead KOLAŠINAC',     pos:'Défenseur', n:3,  age:31, born:'20/06/1993', h:'1m81', club:'Marseille',          caps:62, goals:2, ast:5, debut:'2012', photo:'https://img.sofascore.com/api/v1/player/142148/image', role:'Titulaire',  bio:'Latéral gauche athlétique, puissance physique remarquable.'},
      {id:'bih3',  name:'Anel AHMEDHODŽIĆ',   pos:'Défenseur', n:6,  age:25, born:'26/03/1999', h:'1m89', club:'Sheffield United',   caps:22, goals:3, ast:1, debut:'2021', photo:'https://img.sofascore.com/api/v1/player/825899/image', role:'Titulaire',  bio:'Défenseur central prometteur, leadership naturel.'},
      {id:'bih4',  name:'Ermin BIČAKČIĆ',     pos:'Défenseur', n:5,  age:33, born:'24/01/1990', h:'1m84', club:'Leverkusen',         caps:35, goals:2, ast:1, debut:'2013', photo:'https://img.sofascore.com/api/v1/player/103012/image', role:'Titulaire',  bio:'Défenseur expérimenté, pilier de la défense.'},
      {id:'bih5',  name:'Elvis SARIĆ',         pos:'Défenseur', n:22, age:27, born:'29/07/1996', h:'1m82', club:'Atalanta',           caps:20, goals:1, ast:2, debut:'2022', photo:'', role:'Titulaire',  bio:'Latéral droit dynamique, bon dans les duels.'},
      {id:'bih6',  name:'Amar DŽIDIĆ',         pos:'Milieu',    n:8,  age:28, born:'12/03/1996', h:'1m85', club:'Copenhagen',         caps:25, goals:2, ast:3, debut:'2020', photo:'', role:'Titulaire',  bio:'Milieu défensif robuste, excellent récupérateur.'},
      {id:'bih7',  name:'Amer GOJAK',          pos:'Milieu',    n:14, age:27, born:'13/02/1997', h:'1m82', club:'Dinamo Zagreb',      caps:30, goals:4, ast:6, debut:'2019', photo:'', role:'Titulaire',  bio:'Milieu box-to-box, vision du jeu et pressing.'},
      {id:'bih8',  name:'Edin VIŠĆA',           pos:'Milieu',    n:10, age:34, born:'17/02/1990', h:'1m78', club:'Istanbul Başakşehir',caps:60, goals:12,ast:15,debut:'2011', photo:'https://img.sofascore.com/api/v1/player/109779/image', role:'Titulaire',  bio:'Meneur de jeu vétéran, créativité et expérience.'},
      {id:'bih9',  name:'Ermedin DEMIROVIĆ',   pos:'Attaquant', n:11, age:26, born:'25/03/1998', h:'1m81', club:'Stuttgart',          caps:28, goals:13,ast:5, debut:'2020', photo:'https://img.sofascore.com/api/v1/player/878081/image', role:'Titulaire',  bio:'Attaquant prolifique, finisseur redoutable en Bundesliga.'},
      {id:'bih10', name:'Amir HADŽIĆ',          pos:'Attaquant', n:9,  age:25, born:'09/12/1999', h:'1m82', club:'Hajduk Split',       caps:15, goals:6, ast:3, debut:'2022', photo:'', role:'Titulaire',  bio:'Avant-centre combatif, bonne technique de finition.'},
      {id:'bih11', name:'Haris HAJRADINOVIĆ',  pos:'Attaquant', n:7,  age:28, born:'26/08/1995', h:'1m79', club:'Zenit',              caps:22, goals:5, ast:7, debut:'2019', photo:'https://img.sofascore.com/api/v1/player/254979/image', role:'Titulaire',  bio:'Ailier technique, dribbles et centres précis.'},
      {id:'bih12', name:'Ibrahim ŠEHIĆ',        pos:'Gardien',   n:12, age:36, born:'02/09/1988', h:'1m86', club:'Auxerre',            caps:40, goals:0, ast:0, debut:'2010', photo:'https://img.sofascore.com/api/v1/player/63952/image', role:'Remplaçant', bio:'Gardien vétéran expérimenté.'},
      {id:'bih13', name:'Kenan PIRIĆ',          pos:'Gardien',   n:23, age:30, born:'08/10/1994', h:'1m88', club:'Wigan Athletic',     caps:5,  goals:0, ast:0, debut:'2021', photo:'', role:'Remplaçant', bio:'Troisième gardien fiable.'},
      {id:'bih14', name:'Saša KOVAČEVIĆ',       pos:'Défenseur', n:2,  age:29, born:'14/04/1995', h:'1m80', club:'Ludogorets',         caps:18, goals:0, ast:2, debut:'2021', photo:'', role:'Remplaçant', bio:'Latéral droit régulier, bonne endurance.'},
      {id:'bih15', name:'Nikola ČIČIĆ',         pos:'Défenseur', n:4,  age:28, born:'05/11/1995', h:'1m88', club:'Sarajevo',           caps:12, goals:1, ast:0, debut:'2022', photo:'', role:'Remplaçant', bio:'Défenseur central athlétique.'},
      {id:'bih16', name:'Armin HODŽIĆ',         pos:'Attaquant', n:13, age:30, born:'17/11/1994', h:'1m80', club:'Dinamo Zagreb',      caps:20, goals:7, ast:3, debut:'2018', photo:'', role:'Remplaçant', bio:'Attaquant mobile, pressing et finition.'},
      {id:'bih17', name:'Muhamed BEŠIĆ',        pos:'Milieu',    n:16, age:32, born:'10/09/1992', h:'1m78', club:'Middlesbrough',      caps:42, goals:1, ast:2, debut:'2012', photo:'', role:'Remplaçant', bio:'Milieu défensif dur au marquage, expérience internationale.'},
      {id:'bih18', name:'Dario ŠARAVANJA',      pos:'Milieu',    n:20, age:24, born:'22/06/2000', h:'1m80', club:'Anderlecht',         caps:10, goals:2, ast:3, debut:'2023', photo:'', role:'Remplaçant', bio:'Jeune milieu créatif, bonne progression.'},
    ]
  },


  'Turquie': {
    flag:'🇹🇷', color:'#e30a17', coach:'Vincenzo Montella', formation:'4-2-3-1',
    confederation:'UEFA', bannerImg:'', rating:79,
    posterImg:'images/poster_turkey.png',
    players:[
      {id:'tr1',  name:'Uğurcan ÇAKIR',      pos:'Gardien',   n:1,  age:28, born:'11/07/1996', h:'1m90', club:'Trabzonspor',   caps:44, goals:0, ast:0, debut:'2019', photo:'https://img.sofascore.com/api/v1/player/754330/image', role:'Titulaire',  bio:'Gardien titulaire, réflexes et présence au sol remarquables.'},
      {id:'tr2',  name:'Zeki ÇELIK',          pos:'Défenseur', n:2,  age:27, born:'17/02/1997', h:'1m78', club:'Roma',          caps:36, goals:1, ast:4, debut:'2019', photo:'https://img.sofascore.com/api/v1/player/893008/image', role:'Titulaire',  bio:'Latéral droit athlétique, excellent en montée offensive.'},
      {id:'tr3',  name:'Merih DEMIRAL',       pos:'Défenseur', n:4,  age:26, born:'05/03/1998', h:'1m90', club:'Al-Qadsiah',    caps:45, goals:5, ast:1, debut:'2019', photo:'https://img.sofascore.com/api/v1/player/806968/image', role:'Titulaire',  bio:'Défenseur central dominateur, puissance aérienne.'},
      {id:'tr4',  name:'Çağlar SÖYÜNCÜ',     pos:'Défenseur', n:3,  age:28, born:'23/05/1996', h:'1m86', club:'Atlético Madrid',caps:52, goals:2, ast:1, debut:'2017', photo:'', role:'Titulaire',  bio:'Défenseur polyvalent, lecture du jeu excellente.'},
      {id:'tr5',  name:'Ferdi KADIOGLU',      pos:'Défenseur', n:6,  age:25, born:'07/06/1999', h:'1m77', club:'Brighton',      caps:28, goals:2, ast:5, debut:'2021', photo:'https://img.sofascore.com/api/v1/player/825844/image', role:'Titulaire',  bio:'Latéral gauche technique, excellent dans la montée.'},
      {id:'tr6',  name:'Hakan ÇALHANOĞLU',   pos:'Milieu',    n:8,  age:31, born:'08/02/1994', h:'1m79', club:'Inter Milan',   caps:82, goals:22,ast:18,debut:'2013', photo:'https://img.sofascore.com/api/v1/player/135700/image', role:'Titulaire',  bio:'Capitaine et meilleur joueur, génie du milieu de terrain.'},
      {id:'tr7',  name:'Salih ÖZCAN',         pos:'Milieu',    n:17, age:26, born:'11/03/1998', h:'1m84', club:'Dortmund',      caps:30, goals:1, ast:3, debut:'2021', photo:'', role:'Titulaire',  bio:'Milieu défensif industrieux, pressing et récupération.'},
      {id:'tr8',  name:'Orkun KÖKÇÜ',         pos:'Milieu',    n:10, age:24, born:'25/07/2000', h:'1m83', club:'Benfica',       caps:28, goals:5, ast:7, debut:'2021', photo:'https://img.sofascore.com/api/v1/player/907461/image', role:'Titulaire',  bio:'Milieu créatif, dribbles et vision du jeu.'},
      {id:'tr9',  name:'Arda GÜLER',          pos:'Attaquant', n:22, age:20, born:'25/02/2005', h:'1m76', club:'Real Madrid',   caps:20, goals:8, ast:6, debut:'2023', photo:'https://img.sofascore.com/api/v1/player/1091116/image', role:'Titulaire',  bio:'Prodige du football turc, technique et vision exceptionnelles.'},
      {id:'tr10', name:'Kenan YILDIZ',        pos:'Attaquant', n:7,  age:20, born:'04/05/2005', h:'1m79', club:'Juventus',      caps:16, goals:5, ast:4, debut:'2023', photo:'https://img.sofascore.com/api/v1/player/1149011/image', role:'Titulaire',  bio:'Ailier explosif, talent générationnel de la Turquie.'},
      {id:'tr11', name:'Baris AKTÜRKOĞLU',   pos:'Attaquant', n:9,  age:25, born:'13/08/1999', h:'1m83', club:'Benfica',       caps:24, goals:8, ast:5, debut:'2022', photo:'', role:'Titulaire',  bio:'Attaquant polyvalent, vitesse et finition efficace.'},
      {id:'tr12', name:'Altay BAYINDIR',      pos:'Gardien',   n:25, age:26, born:'19/04/1998', h:'1m97', club:'Man United',    caps:12, goals:0, ast:0, debut:'2022', photo:'', role:'Remplaçant', bio:'Grande envergure, promesse du gardiennage turc.'},
      {id:'tr13', name:'Mert GÜNOK',          pos:'Gardien',   n:23, age:35, born:'25/03/1989', h:'1m88', club:'Beşiktaş',     caps:30, goals:0, ast:0, debut:'2015', photo:'', role:'Remplaçant', bio:'Troisième gardien vétéran, fiabilité en club.'},
      {id:'tr14', name:'Samet AKAYDIN',       pos:'Défenseur', n:5,  age:27, born:'14/02/1997', h:'1m89', club:'Fenerbahçe',   caps:18, goals:1, ast:0, debut:'2022', photo:'', role:'Remplaçant', bio:'Défenseur central athlétique, bon jeu aérien.'},
      // ─── GARDIENS ────────────────────────────
      { id: 'ht0', name: 'Johny PLACIDE', pos: 'Gardien', n: 0, age: 38, born: 'January 29, 1988', club: 'Bastia', caps: 79, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Alexandre PIERRE', pos: 'Gardien', n: 0, age: 25, born: 'February 25, 2001', club: 'Sochaux', caps: 14, goals: 0, ast: 0, photo: '', role: 'Remplaçant', bio: '' },
      { id: 'ht0', name: 'Josué DUVERGER', pos: 'Gardien', n: 0, age: 26, born: 'April 27, 2000', club: 'Cosmos Koblenz', caps: 6, goals: 0, ast: 0, photo: '', role: 'Remplaçant', bio: '' },
      // ─── DÉFENSEURS ────────────────────────────
      { id: 'ht0', name: 'Ricardo ADÉ', pos: 'Défenseur', n: 0, age: 36, born: 'May 21, 1990', club: 'LDU Quito', caps: 57, goals: 2, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Carlens ARCUS', pos: 'Défenseur', n: 0, age: 29, born: 'June 28, 1996', club: 'Angers', caps: 51, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Martin EXPÉRIENCE', pos: 'Défenseur', n: 0, age: 27, born: 'March 9, 1999', club: 'Nancy', caps: 19, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Jean-kévin DUVERNE', pos: 'Défenseur', n: 0, age: 28, born: 'July 12, 1997', club: 'Gent', caps: 15, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Duke LACROIX', pos: 'Défenseur', n: 0, age: 32, born: 'October 14, 1993', club: 'Colorado Springs Switchbacks', caps: 14, goals: 2, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Wilguens PAUGAIN', pos: 'Défenseur', n: 0, age: 24, born: 'August 24, 2001', club: 'Zulte Waregem', caps: 6, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Hannes DELCROIX', pos: 'Défenseur', n: 0, age: 27, born: 'February 28, 1999', club: 'Lugano', caps: 5, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Keeto THERMONCY', pos: 'Défenseur', n: 0, age: 20, born: 'March 29, 2006', club: 'Young Boys', caps: 1, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      // ─── MILIEUX ────────────────────────────
      { id: 'ht0', name: 'Leverton PIERRE', pos: 'Milieu', n: 0, age: 28, born: 'March 9, 1998', club: 'Vizela', caps: 33, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Danley Jean JACQUES', pos: 'Milieu', n: 0, age: 26, born: 'May 20, 2000', club: 'Philadelphia Union', caps: 28, goals: 6, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Carl SAINTÉ', pos: 'Milieu', n: 0, age: 23, born: 'August 9, 2002', club: 'El Paso Locomotive FC', caps: 25, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Jean-ricner BELLEGARDE', pos: 'Milieu', n: 0, age: 27, born: 'June 27, 1998', club: 'Wolverhampton Wanderers', caps: 8, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Woodensky PIERRE', pos: 'Milieu', n: 0, age: 21, born: 'December 30, 2004', club: 'Violette', caps: 1, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'civ4', name: 'Simon DELI', pos: 'Milieu', n: 0, age: 25, born: 'July 29, 2000', club: 'Tatran Prešov', caps: 0, goals: 0, ast: 0, photo: 'https://img.sofascore.com/api/v1/player/326419/image', role: 'Titulaire', bio: 'Défenseur central expérimenté, lecture du jeu solide.' },
      // ─── ATTAQUANTS ────────────────────────────
      { id: 'ht0', name: 'Duckens NAZON', pos: 'Attaquant', n: 0, age: 32, born: 'April 7, 1994', club: 'Esteghlal', caps: 76, goals: 44, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Frantzdy PIERROT', pos: 'Attaquant', n: 0, age: 31, born: 'March 29, 1995', club: 'aykur Rizespor', caps: 49, goals: 33, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Derrick Etienne JR.', pos: 'Attaquant', n: 0, age: 29, born: 'November 25, 1996', club: 'Toronto FC', caps: 46, goals: 8, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Louicius DEEDSON', pos: 'Attaquant', n: 0, age: 25, born: 'February 11, 2001', club: 'FC Dallas', caps: 30, goals: 10, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Ruben PROVIDENCE', pos: 'Attaquant', n: 0, age: 24, born: 'July 7, 2001', club: 'Almere City', caps: 13, goals: 2, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Josué CASIMIR', pos: 'Attaquant', n: 0, age: 24, born: 'September 24, 2001', club: 'Auxerre', caps: 5, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Yassin FORTUNÉ', pos: 'Attaquant', n: 0, age: 27, born: 'January 30, 1999', club: 'Vizela', caps: 3, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Wilson ISIDOR', pos: 'Attaquant', n: 0, age: 25, born: 'August 27, 2000', club: 'Sunderland', caps: 2, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'ht0', name: 'Lenny JOSEPH', pos: 'Attaquant', n: 0, age: 25, born: 'October 12, 2000', club: 'Ferencváros', caps: 0, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      {id:'civ6',  name:'Ibrahim SANGARÉ',    pos:'Milieu',    n:6,  age:27, born:'02/02/1997', h:'1m90', club:'Nottm Forest',    caps:28, goals:2, ast:3, debut:'2021', photo:'https://img.sofascore.com/api/v1/player/843754/image', role:'Titulaire',  bio:'Milieu défensif colossal, domination physique totale.'},
      {id:'civ7',  name:'Seko FOFANA',        pos:'Milieu',    n:10, age:29, born:'07/05/1995', h:'1m87', club:'Al-Qadsiah',      caps:35, goals:5, ast:7, debut:'2019', photo:'https://img.sofascore.com/api/v1/player/191188/image', role:'Titulaire',  bio:'Milieu box-to-box d\'exception, élu meilleur joueur africain.'},
      {id:'civ8',  name:'Franck KESSIÉ',      pos:'Milieu',    n:8,  age:28, born:'19/12/1996', h:'1m83', club:'Al-Ahli',         caps:70, goals:15,ast:8, debut:'2016', photo:'https://img.sofascore.com/api/v1/player/359226/image', role:'Titulaire',  bio:'Le Président, combattivité et buts importants.'},
      {id:'civ9',  name:'Wilfried ZAHA',      pos:'Attaquant', n:7,  age:32, born:'10/11/1992', h:'1m79', club:'Galatasaray',     caps:12, goals:4, ast:3, debut:'2023', photo:'https://img.sofascore.com/api/v1/player/111850/image', role:'Titulaire',  bio:'Ailier vif, dribbles dévastateurs, naturalisé en 2023.'},
      {id:'civ10', name:'Sébastien HALLER',   pos:'Attaquant', n:9,  age:30, born:'22/06/1994', h:'1m91', club:'Dortmund',        caps:36, goals:16,ast:5, debut:'2018', photo:'https://img.sofascore.com/api/v1/player/149731/image', role:'Titulaire',  bio:'Avant-centre imposant, retour magnifique après cancer.'},
      {id:'civ11', name:'Simon ADINGRA',      pos:'Attaquant', n:11, age:23, born:'28/01/2002', h:'1m72', club:'Brighton',        caps:15, goals:5, ast:4, debut:'2022', photo:'https://img.sofascore.com/api/v1/player/1110842/image', role:'Titulaire',  bio:'Ailier rapide, vainqueur CAN 2024, future star africaine.'},
      {id:'civ12', name:'Yahia FOFANA',       pos:'Gardien',   n:16, age:28, born:'09/06/1996', h:'1m92', club:'Chelsea',         caps:15, goals:0, ast:0, debut:'2021', photo:'https://img.sofascore.com/api/v1/player/877977/image', role:'Remplaçant', bio:'Gardien de grande taille, bonne couverture aérienne.'},
      {id:'civ13', name:'Serge AURIER',       pos:'Défenseur', n:24, age:32, born:'24/12/1992', h:'1m81', club:'Al-Duhail',       caps:68, goals:6, ast:8, debut:'2012', photo:'https://img.sofascore.com/api/v1/player/105697/image', role:'Remplaçant', bio:'Latéral droit expérimenté, frappe puissante.'},
      {id:'civ14', name:'Ismaël DIALLO',      pos:'Défenseur', n:15, age:23, born:'22/03/2001', h:'1m85', club:'Augsbourg',       caps:8,  goals:0, ast:0, debut:'2023', photo:'', role:'Remplaçant', bio:'Défenseur central jeune en progression.'},
      {id:'civ15', name:'Stéphane SINGO',     pos:'Défenseur', n:20, age:26, born:'12/07/1998', h:'1m80', club:'Genk',            caps:10, goals:0, ast:1, debut:'2023', photo:'', role:'Remplaçant', bio:'Défenseur polyvalent, bon dans l\'une-contre-un.'},
      {id:'civ16', name:'Oumar DIAKHABY',     pos:'Défenseur', n:14, age:29, born:'11/08/1995', h:'1m87', club:'Huesca',          caps:6,  goals:0, ast:0, debut:'2022', photo:'', role:'Remplaçant', bio:'Défenseur central expérimenté en Liga.'},
      {id:'civ17', name:'Jean-Michaël SERI',  pos:'Milieu',    n:17, age:33, born:'19/07/1991', h:'1m68', club:'Al-Shabab',       caps:42, goals:4, ast:9, debut:'2015', photo:'', role:'Remplaçant', bio:'Milieu technique vétéran, élégance et précision.'},
      {id:'civ18', name:'Joël ANAK',          pos:'Milieu',    n:19, age:25, born:'01/04/1999', h:'1m76', club:'Havre AC',        caps:6,  goals:1, ast:2, debut:'2023', photo:'', role:'Remplaçant', bio:'Jeune milieu créatif, en progression.'},
      {id:'civ19', name:'Jérémie BOGA',       pos:'Attaquant', n:22, age:28, born:'03/01/1997', h:'1m72', club:'Atalanta',        caps:18, goals:4, ast:5, debut:'2021', photo:'https://img.sofascore.com/api/v1/player/367056/image', role:'Remplaçant', bio:'Ailier dribbleur, explosivité et technique.'},
      {id:'civ20', name:'Azzedine OUNAS',     pos:'Attaquant', n:23, age:28, born:'01/08/1996', h:'1m74', club:'Nice',            caps:8,  goals:2, ast:2, debut:'2023', photo:'', role:'Remplaçant', bio:'Ailier technique, capable de créer du danger.'},
    ]
  },

  'Suède': {
    flag:'🇸🇪', color:'#006aa7', coach:'Jon Dahl Tomasson', formation:'4-3-3',
    confederation:'UEFA', bannerImg:'', rating:77,
    posterImg:'images/poster_sweden.png',
    players:[
      // ─── GARDIENS ────────────────────────────
      { id: 'tr0', name: 'Uğurcan ÇAKIR', pos: 'Gardien', n: 0, age: 30, born: 'April 5, 1996', club: 'Galatasaray', caps: 38, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Mert GÜNOK', pos: 'Gardien', n: 0, age: 37, born: 'March 1, 1989', club: 'Fenerbahçe', caps: 37, goals: 0, ast: 0, photo: '', role: 'Remplaçant', bio: '' },
      { id: 'tr0', name: 'Altay BAYINDIR', pos: 'Gardien', n: 0, age: 28, born: 'April 14, 1998', club: 'Manchester United', caps: 11, goals: 0, ast: 0, photo: '', role: 'Remplaçant', bio: '' },
      { id: 'tr0', name: 'Ersin DESTANOĞLU', pos: 'Gardien', n: 0, age: 25, born: 'January 1, 2001', club: 'Beşiktaş', caps: 0, goals: 0, ast: 0, photo: '', role: 'Remplaçant', bio: '' },
      { id: 'tr0', name: 'Muhammed ŞENGEZER', pos: 'Gardien', n: 0, age: 29, born: 'January 5, 1997', club: 'stanbul Başakşehir', caps: 0, goals: 0, ast: 0, photo: '', role: 'Remplaçant', bio: '' },
      // ─── DÉFENSEURS ────────────────────────────
      { id: 'tr0', name: 'Merih DEMIRAL', pos: 'Défenseur', n: 0, age: 28, born: 'March 5, 1998', club: 'Al-Ahli', caps: 61, goals: 6, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Zeki ÇELIK', pos: 'Défenseur', n: 0, age: 29, born: 'February 17, 1997', club: 'Roma', caps: 59, goals: 3, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Çağlar SÖYÜNCÜ', pos: 'Défenseur', n: 0, age: 30, born: 'May 23, 1996', club: 'Fenerbahçe', caps: 59, goals: 2, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Mert MÜLDÜR', pos: 'Défenseur', n: 0, age: 27, born: 'April 3, 1999', club: 'Fenerbahçe', caps: 43, goals: 3, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Ferdi KADIOĞLU', pos: 'Défenseur', n: 0, age: 26, born: 'October 7, 1999', club: 'Brighton & Hove Albion', caps: 30, goals: 2, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Ozan KABAK', pos: 'Défenseur', n: 0, age: 26, born: 'March 25, 2000', club: 'TSG Hoffenheim', caps: 28, goals: 2, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Abdülkerim BARDAKCI', pos: 'Défenseur', n: 0, age: 31, born: 'September 7, 1994', club: 'Galatasaray', caps: 26, goals: 2, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Eren ELMALI', pos: 'Défenseur', n: 0, age: 25, born: 'July 7, 2000', club: 'Galatasaray', caps: 21, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Samet AKAYDIN', pos: 'Défenseur', n: 0, age: 32, born: 'May 13, 1994', club: 'aykur Rizespor', caps: 18, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Yusuf AKÇIÇEK', pos: 'Défenseur', n: 0, age: 20, born: 'January 25, 2006', club: 'Al-Hilal', caps: 3, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Mustafa ESKIHELLAÇ', pos: 'Défenseur', n: 0, age: 29, born: 'May 5, 1997', club: 'Trabzonspor', caps: 3, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Ahmetcan KAPLAN', pos: 'Défenseur', n: 0, age: 23, born: 'January 16, 2003', club: 'NEC', caps: 0, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      // ─── MILIEUX ────────────────────────────
      { id: 'tr0', name: 'Hakan ÇALHANOĞLU', pos: 'Milieu', n: 0, age: 32, born: 'February 8, 1994', club: 'Inter Milan', caps: 104, goals: 22, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Kaan AYHAN', pos: 'Milieu', n: 0, age: 31, born: 'November 10, 1994', club: 'Galatasaray', caps: 72, goals: 5, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Orkun KÖKÇÜ', pos: 'Milieu', n: 0, age: 25, born: 'December 29, 2000', club: 'Beşiktaş', caps: 48, goals: 3, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'İsmail YÜKSEK', pos: 'Milieu', n: 0, age: 27, born: 'January 26, 1999', club: 'Fenerbahçe', caps: 31, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Salih ÖZCAN', pos: 'Milieu', n: 0, age: 28, born: 'January 11, 1998', club: 'Borussia Dortmund', caps: 28, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Atakan KARAZOR', pos: 'Milieu', n: 0, age: 29, born: 'October 13, 1996', club: 'VfB Stuttgart', caps: 2, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Demir Ege TIKNAZ', pos: 'Milieu', n: 0, age: 21, born: 'August 17, 2004', club: 'Braga', caps: 1, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      // ─── ATTAQUANTS ────────────────────────────
      { id: 'tr0', name: 'Kerem AKTÜRKOĞLU', pos: 'Attaquant', n: 0, age: 27, born: 'October 21, 1998', club: 'Fenerbahçe', caps: 51, goals: 15, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'İrfan Can KAHVECI', pos: 'Attaquant', n: 0, age: 30, born: 'July 15, 1995', club: 'Kasımpaşa', caps: 45, goals: 6, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Barış Alper YILMAZ', pos: 'Attaquant', n: 0, age: 26, born: 'May 23, 2000', club: 'Galatasaray', caps: 33, goals: 2, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Arda GÜLER', pos: 'Attaquant', n: 0, age: 21, born: 'February 25, 2005', club: 'Real Madrid', caps: 28, goals: 6, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Kenan YILDIZ', pos: 'Attaquant', n: 0, age: 21, born: 'May 4, 2005', club: 'Juventus', caps: 28, goals: 5, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Yunus AKGÜN', pos: 'Attaquant', n: 0, age: 25, born: 'July 7, 2000', club: 'Galatasaray', caps: 17, goals: 3, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Oğuz AYDIN', pos: 'Attaquant', n: 0, age: 25, born: 'October 27, 2000', club: 'Fenerbahçe', caps: 9, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Deniz GÜL', pos: 'Attaquant', n: 0, age: 21, born: 'July 2, 2004', club: 'Porto', caps: 6, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Yusuf SARI', pos: 'Attaquant', n: 0, age: 27, born: 'November 20, 1998', club: 'stanbul Başakşehir', caps: 6, goals: 1, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Can UZUN', pos: 'Attaquant', n: 0, age: 20, born: 'November 11, 2005', club: 'Eintracht Frankfurt', caps: 4, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
      { id: 'tr0', name: 'Aral ŞIMŞIR', pos: 'Attaquant', n: 0, age: 23, born: 'June 19, 2002', club: 'Midtjylland', caps: 0, goals: 0, ast: 0, photo: '', role: 'Titulaire', bio: '' },
    ]
  },

  'Irak': {
    flag:'🇮🇶', color:'007a3d', coach:'Jesús Casas', formation:'4-3-3',
    confederation:'AFC', bannerImg:'', rating:67,
    players:[
      {id:'iq1',  name:'Jalal HASSAN',        pos:'Gardien',   n:1,  age:34, born:'14/09/1990', h:'1m89', club:'Al-Zawraa',      caps:65, goals:0, ast:0, debut:'2012', photo:'', role:'Titulaire',  bio:'Gardien emblématique de l\'Irak, expérience précieuse.'},
      {id:'iq2',  name:'Ali ADNAN',           pos:'Défenseur', n:3,  age:31, born:'19/12/1993', h:'1m83', club:'Al-Quwa Al-Jawiya',caps:75,goals:3, ast:6, debut:'2012', photo:'https://img.sofascore.com/api/v1/player/331429/image', role:'Titulaire',  bio:'Capitaine emblématique, latéral gauche technique.'},
      {id:'iq3',  name:'Ahmed IBRAHIM',       pos:'Défenseur', n:5,  age:28, born:'22/03/1996', h:'1m86', club:'Al-Zawraa',      caps:40, goals:2, ast:1, debut:'2018', photo:'', role:'Titulaire',  bio:'Défenseur central solide, excellent dans les airs.'},
      {id:'iq4',  name:'Rebin SULAKA',        pos:'Défenseur', n:6,  age:25, born:'16/01/1999', h:'1m84', club:'IFK Göteborg',   caps:28, goals:1, ast:0, debut:'2020', photo:'', role:'Titulaire',  bio:'Défenseur kurde irakien, bonne couverture de zone.'},
      {id:'iq5',  name:'Waleed SALIM',        pos:'Défenseur', n:22, age:27, born:'11/07/1997', h:'1m80', club:'Al-Shorta',      caps:20, goals:0, ast:2, debut:'2021', photo:'', role:'Titulaire',  bio:'Latéral droit combatif, bon dans la relance.'},
      {id:'iq6',  name:'Amjad ATTWAN',        pos:'Milieu',    n:8,  age:29, born:'04/05/1995', h:'1m80', club:'Al-Zawraa',      caps:50, goals:5, ast:8, debut:'2017', photo:'', role:'Titulaire',  bio:'Milieu clé de l\'Irak, moteur du jeu.'},
      {id:'iq7',  name:'Hussein ALI',         pos:'Milieu',    n:6,  age:27, born:'17/09/1997', h:'1m78', club:'Al-Quwa Al-Jawiya',caps:35,goals:4, ast:5, debut:'2019', photo:'', role:'Titulaire',  bio:'Milieu défensif, récupération et organisation.'},
      {id:'iq8',  name:'Saad NATIQ',          pos:'Milieu',    n:14, age:26, born:'09/02/1998', h:'1m79', club:'Al-Zawraa',      caps:28, goals:3, ast:6, debut:'2020', photo:'', role:'Titulaire',  bio:'Milieu créatif, vision du jeu et passes laser.'},
      {id:'iq9',  name:'Ayman HUSSEIN',       pos:'Attaquant', n:10, age:27, born:'10/03/1997', h:'1m81', club:'Al-Shorta',      caps:45, goals:18,ast:7, debut:'2018', photo:'https://img.sofascore.com/api/v1/player/812999/image', role:'Titulaire',  bio:'Star offensive irakienne, technique et finition.'},
      {id:'iq10', name:'Mohanad ALI',         pos:'Attaquant', n:9,  age:26, born:'08/11/1998', h:'1m83', club:'Al-Quwa Al-Jawiya',caps:38,goals:14,ast:6, debut:'2019', photo:'', role:'Titulaire',  bio:'Attaquant redoutable, buteur régulier en Asie.'},
      {id:'iq11', name:'Bashar RESAN',        pos:'Attaquant', n:11, age:25, born:'02/07/1999', h:'1m78', club:'Al-Zawraa',      caps:25, goals:8, ast:5, debut:'2021', photo:'', role:'Titulaire',  bio:'Ailier rapide, dribbles et centres précis.'},
      {id:'iq12', name:'Mohammed HAMEED',     pos:'Gardien',   n:18, age:26, born:'14/04/1998', h:'1m88', club:'Al-Quwa Al-Jawiya',caps:12, goals:0, ast:0, debut:'2022', photo:'', role:'Remplaçant', bio:'Doublure fiable, bon avec les pieds.'},
      {id:'iq13', name:'Dhurgham ISMAEL',     pos:'Gardien',   n:23, age:28, born:'03/02/1996', h:'1m86', club:'Al-Zawraa',      caps:5,  goals:0, ast:0, debut:'2023', photo:'', role:'Remplaçant', bio:'Troisième gardien solide.'},
      {id:'iq14', name:'Yaser KASIM',         pos:'Milieu',    n:16, age:32, born:'10/05/1992', h:'1m78', club:'Al-Shorta',      caps:48, goals:6, ast:4, debut:'2013', photo:'', role:'Remplaçant', bio:'Milieu vétéran, expérience internationale précieuse.'},
      {id:'iq15', name:'Ameer AL-SAFI',       pos:'Milieu',    n:20, age:28, born:'17/06/1996', h:'1m80', club:'Al-Zawraa',      caps:20, goals:2, ast:3, debut:'2021', photo:'', role:'Remplaçant', bio:'Milieu relayeur fiable, bon pressing.'},
      {id:'iq16', name:'Abbas ATIYAH',        pos:'Attaquant', n:15, age:27, born:'21/08/1997', h:'1m77', club:'Al-Quwa Al-Jawiya',caps:18, goals:5, ast:3, debut:'2021', photo:'', role:'Remplaçant', bio:'Attaquant mobile, capable depuis le banc.'},
      {id:'iq17', name:'Alaa ALI',            pos:'Défenseur', n:2,  age:30, born:'08/01/1994', h:'1m82', club:'Al-Shorta',      caps:25, goals:1, ast:1, debut:'2019', photo:'', role:'Remplaçant', bio:'Latéral droit fiable, bon positionnement.'},
    ]
  },

  'RD Congo': {
    flag:'🇨🇩', color:'#007fff', coach:'Sébastien Desabre', formation:'4-3-3',
    confederation:'CAF', bannerImg:'', rating:72,
    players:[
      {id:'cod1',  name:'Joël KIASSUMBUA',    pos:'Gardien',   n:1,  age:33, born:'19/03/1991', h:'1m88', club:'Gent',           caps:42, goals:0, ast:0, debut:'2013', photo:'', role:'Titulaire',  bio:'Gardien expérimenté, réflexes et présence aérienne.'},
      {id:'cod2',  name:'Chancel MBEMBA',     pos:'Défenseur', n:4,  age:30, born:'08/08/1994', h:'1m78', club:'Marseille',      caps:55, goals:3, ast:2, debut:'2014', photo:'https://img.sofascore.com/api/v1/player/238612/image', role:'Titulaire',  bio:'Capitaine défensif, agressivité et leadership.'},
      {id:'cod3',  name:'Christian LUYINDAMA',pos:'Défenseur', n:5,  age:31, born:'09/10/1992', h:'1m88', club:'Al-Ain',         caps:40, goals:2, ast:1, debut:'2015', photo:'https://img.sofascore.com/api/v1/player/867191/image', role:'Titulaire',  bio:'Défenseur central imposant, domination physique.'},
      {id:'cod4',  name:'Nayel MEHSSATOU',    pos:'Défenseur', n:3,  age:26, born:'25/02/1998', h:'1m84', club:'Troyes',         caps:18, goals:0, ast:2, debut:'2022', photo:'https://img.sofascore.com/api/v1/player/1064174/image', role:'Titulaire',  bio:'Latéral gauche technique, bonne montée offensive.'},
      {id:'cod5',  name:'Ngonda MUZINGA',     pos:'Défenseur', n:2,  age:28, born:'05/09/1996', h:'1m83', club:'Huesca',         caps:22, goals:1, ast:1, debut:'2021', photo:'', role:'Titulaire',  bio:'Latéral droit combatif, bonne relance.'},
      {id:'cod6',  name:'Gaël KAKUTA',        pos:'Milieu',    n:8,  age:33, born:'21/06/1991', h:'1m74', club:'Amiens',         caps:40, goals:8, ast:10,debut:'2011', photo:'https://img.sofascore.com/api/v1/player/46387/image', role:'Titulaire',  bio:'Milieu technique vétéran, dribbles et créativité.'},
      {id:'cod7',  name:'Samuel MOUTOUSSAMY', pos:'Milieu',    n:6,  age:29, born:'25/04/1995', h:'1m83', club:'Getafe',         caps:28, goals:3, ast:4, debut:'2020', photo:'https://img.sofascore.com/api/v1/player/892624/image', role:'Titulaire',  bio:'Milieu défensif robuste, pressing et récupération.'},
      {id:'cod8',  name:'Théo BONGONDA',      pos:'Milieu',    n:14, age:29, born:'20/11/1995', h:'1m75', club:'Genk',           caps:25, goals:5, ast:8, debut:'2020', photo:'', role:'Titulaire',  bio:'Milieu offensif rapide, bonne finition.'},
      {id:'cod9',  name:'Cédric BAKAMBU',     pos:'Attaquant', n:10, age:33, born:'05/04/1991', h:'1m84', club:'OM/AL-Qadsiah', caps:52, goals:22,ast:8, debut:'2013', photo:'https://img.sofascore.com/api/v1/player/115665/image', role:'Titulaire',  bio:'Attaquant vedette, finisseur redoutable en carrière.'},
      {id:'cod10', name:'Silas WISSA',        pos:'Attaquant', n:9,  age:25, born:'03/08/1999', h:'1m71', club:'Brentford',      caps:20, goals:8, ast:5, debut:'2022', photo:'', role:'Titulaire',  bio:'Attaquant explosif en Premier League, dribbles redoutables.'},
      {id:'cod11', name:'Jonathan BOLINGI',   pos:'Attaquant', n:11, age:32, born:'11/11/1992', h:'1m84', club:'Anderlecht',     caps:38, goals:12,ast:6, debut:'2014', photo:'', role:'Titulaire',  bio:'Ailier puissant, vitesse et centres précis.'},
      {id:'cod12', name:'Lionel MPASI',       pos:'Gardien',   n:16, age:27, born:'22/07/1997', h:'1m90', club:'RD Congo',       caps:8,  goals:0, ast:0, debut:'2022', photo:'', role:'Remplaçant', bio:'Jeune gardien en développement.'},
      {id:'cod13', name:'Marcel TISSERAND',   pos:'Défenseur', n:15, age:31, born:'25/01/1993', h:'1m87', club:'Fenerbahçe',     caps:30, goals:2, ast:0, debut:'2018', photo:'https://img.sofascore.com/api/v1/player/338651/image', role:'Remplaçant', bio:'Défenseur central physique, expérience européenne.'},
      {id:'cod14', name:'Arthur MASUAKU',     pos:'Défenseur', n:3,  age:30, born:'07/11/1993', h:'1m78', club:'Besiktas',       caps:28, goals:1, ast:4, debut:'2018', photo:'https://img.sofascore.com/api/v1/player/174975/image', role:'Remplaçant', bio:'Latéral gauche offensif, bon passeur.'},
      {id:'cod15', name:'Tobias BADIBANGA',   pos:'Milieu',    n:17, age:32, born:'08/07/1992', h:'1m73', club:'RD Congo',       caps:18, goals:3, ast:5, debut:'2018', photo:'', role:'Remplaçant', bio:'Milieu offensif technique, bonne finition.'},
      {id:'cod16', name:'Yannick BOLASIE',    pos:'Attaquant', n:22, age:35, born:'24/05/1989', h:'1m88', club:'RD Congo',       caps:48, goals:8, ast:9, debut:'2012', photo:'https://img.sofascore.com/api/v1/player/46620/image', role:'Remplaçant', bio:'Ailier vétéran, dribbles spectaculaires et expérience.'},
      {id:'cod17', name:'Chadrac AKOLO',      pos:'Attaquant', n:20, age:29, born:'06/04/1995', h:'1m84', club:'Schalke 04',     caps:22, goals:6, ast:3, debut:'2020', photo:'', role:'Remplaçant', bio:'Attaquant polyvalent, pressing et finition efficace.'},
    ]
  },

};