const QUIZZ_DATA = {
    easy: [
        { q: "Qui a gagné la Coupe du Monde 2022 ?", o: ["France", "Argentine", "Brésil", "Maroc"], a: 1 },
        { q: "Dans quel pays s'est déroulée la Coupe du Monde 1998 ?", o: ["Italie", "France", "Allemagne", "Brésil"], a: 1 },
        { q: "Combien de fois le Brésil a-t-il gagné la Coupe du Monde ?", o: ["3", "4", "5", "6"], a: 2 },
        { q: "Quel joueur est surnommé 'Le Roi' ?", o: ["Zidane", "Maradona", "Pelé", "Messi"], a: 2 },
        { q: "Tous les combien d'années a lieu la Coupe du Monde ?", o: ["2 ans", "3 ans", "4 ans", "5 ans"], a: 2 },
        { q: "Quelle équipe a gagné en 2014 ?", o: ["Argentine", "Allemagne", "Pays-Bas", "Brésil"], a: 1 },
        { q: "Quel pays a accueilli la première Coupe du Monde en 1930 ?", o: ["Brésil", "Uruguay", "France", "Argentine"], a: 1 },
        { q: "Qui est le meilleur buteur de l'histoire de la France en Coupe du Monde ?", o: ["Mbappé", "Just Fontaine", "Zidane", "Henry"], a: 1 },
        { q: "En quelle année Zidane a-t-il pris sa retraite internationale après une finale ?", o: ["2002", "2006", "2010", "1998"], a: 1 },
        { q: "Quelle est la couleur principale du maillot de l'Italie ?", o: ["Rouge", "Bleu", "Blanc", "Vert"], a: 1 },
        { q: "Qui a marqué deux buts en finale 1998 ?", o: ["Henry", "Petit", "Zidane", "Djorkaeff"], a: 2 },
        { q: "Quelle équipe joue en 'jaune et vert' ?", o: ["Australie", "Brésil", "Colombie", "Afrique du Sud"], a: 1 },
        { q: "Quel pays a gagné la Coupe du Monde 2010 ?", o: ["Espagne", "Pays-Bas", "Allemagne", "Uruguay"], a: 0 },
        { q: "Combien de joueurs par équipe sont sur le terrain ?", o: ["10", "11", "12", "7"], a: 1 },
        { q: "Quel est le trophée de la Coupe du Monde ?", o: ["Coupe Jules Rimet", "Coupe du Monde FIFA", "Ballon d'Or", "Bouclier Brennus"], a: 1 },
        { q: "Cristiano Ronaldo joue pour quel pays ?", o: ["Brésil", "Espagne", "Portugal", "Italie"], a: 2 },
        { q: "Lionel Messi est né dans quel pays ?", o: ["Espagne", "Mexique", "Argentine", "Uruguay"], a: 2 },
        { q: "Quel pays a accueilli la Coupe du Monde 2018 ?", o: ["Russie", "Qatar", "Brésil", "Afrique du Sud"], a: 0 },
        { q: "Qui a gagné la Coupe du Monde 2002 ?", o: ["Allemagne", "Brésil", "France", "Italie"], a: 1 },
        { q: "Quelle équipe est surnommée la 'Roja' ?", o: ["Portugal", "Espagne", "Argentine", "Mexique"], a: 1 },
        { q: "Quel est le temps réglementaire d'un match (hors arrêts de jeu) ?", o: ["80 min", "90 min", "100 min", "45 min"], a: 1 },
        { q: "Quel pays est l'hôte de la Coupe du Monde 2026 avec les USA et le Canada ?", o: ["Panama", "Mexique", "Costa Rica", "Brésil"], a: 1 },
        { q: "Quel joueur porte souvent le numéro 10 pour le Brésil (actuellement) ?", o: ["Vinicius", "Neymar", "Rodrygo", "Richarlison"], a: 1 },
        { q: "En quelle année a eu lieu la Coupe du Monde en Afrique du Sud ?", o: ["2006", "2010", "2014", "2002"], a: 1 },
        { q: "Quelle nation a gagné la Coupe du Monde 1966 à domicile ?", o: ["Allemagne", "Angleterre", "France", "Argentine"], a: 1 },
        { q: "Quel gardien a un gant d'or ?", o: ["Le plus petit", "Le meilleur du tournoi", "Celui qui ne prend pas de but", "Le capitaine"], a: 1 },
        { q: "Quel pays a le record de participations ?", o: ["Allemagne", "Brésil", "Italie", "Argentine"], a: 1 },
        { q: "Quel continent n'a jamais accueilli la Coupe du Monde ?", o: ["Afrique", "Asie", "Océanie", "Amérique du Nord"], a: 2 },
        { q: "Qui était l'entraîneur de la France en 1998 ?", o: ["Roger Lemerre", "Aimé Jacquet", "Michel Hidalgo", "Raymond Domenech"], a: 1 },
        { q: "Quel pays a gagné en 2006 ?", o: ["France", "Italie", "Allemagne", "Portugal"], a: 1 },
        { q: "Kylian Mbappé joue pour quelle nation ?", o: ["Cameroun", "Sénégal", "France", "Belgique"], a: 2 },
        { q: "Quel pays a perdu la finale 2022 ?", o: ["Maroc", "Croatie", "France", "Argentine"], a: 2 },
        { q: "Quelle ville a accueilli la finale 1998 ?", o: ["Lyon", "Marseille", "Saint-Denis", "Paris"], a: 2 },
        { q: "Quelle ville a accueilli la finale 2022 ?", o: ["Doha", "Lusail", "Al-Khor", "Al-Rayyan"], a: 1 },
        { q: "Quel pays a gagné la Coupe du Monde 1978 ?", o: ["Pays-Bas", "Brésil", "Argentine", "Italie"], a: 2 },
        { q: "Quel joueur est célèbre pour sa 'Main de Dieu' ?", o: ["Pelé", "Maradona", "Messi", "Suarez"], a: 1 },
        { q: "Quelle équipe porte un maillot blanc avec une bande rouge diagonale ?", o: ["Pologne", "Pérou", "Turquie", "Chili"], a: 1 },
        { q: "Quelle équipe nationale est surnommée les 'Lions Indomptables' ?", o: ["Sénégal", "Cameroun", "Côte d'Ivoire", "Maroc"], a: 1 },
        { q: "Quel pays a gagné deux Coupes du Monde d'affilée en 1958 et 1962 ?", o: ["Italie", "Brésil", "Allemagne", "Uruguay"], a: 1 },
        { q: "Quelle nation a accueilli le tournoi en 1994 ?", o: ["Italie", "USA", "Mexique", "France"], a: 1 },
        { q: "Quel est le nom du ballon officiel de 2022 ?", o: ["Jabulani", "Al Rihla", "Brazuca", "Telstar"], a: 1 },
        { q: "Qui a marqué le but de la victoire en finale 2010 ?", o: ["Villa", "Xavi", "Iniesta", "Torres"], a: 2 },
        { q: "Combien d'équipes participaient au Mondial 2022 ?", o: ["24", "32", "48", "16"], a: 1 },
        { q: "Quelle équipe porte le surnom d'Albiceleste ?", o: ["Uruguay", "Italie", "Argentine", "Grèce"], a: 2 },
        { q: "Quel pays a organisé le Mondial 2006 ?", o: ["Japon", "Allemagne", "Italie", "Brésil"], a: 1 },
        { q: "Quel pays a gagné en 1954 ?", o: ["Hongrie", "Allemagne de l'Ouest", "Brésil", "Autriche"], a: 1 },
        { q: "Quel pays a gagné la Coupe du Monde 1934 ?", o: ["Italie", "Tchécoslovaquie", "Uruguay", "Allemagne"], a: 0 },
        { q: "Qui est le meilleur buteur de l'édition 2022 ?", o: ["Messi", "Mbappé", "Giroud", "Alvarez"], a: 1 },
        { q: "Quel pays a accueilli le Mondial 1982 ?", o: ["Mexique", "Espagne", "Argentine", "Italie"], a: 1 },
        { q: "Quel pays a gagné la Coupe du Monde 1990 ?", o: ["Argentine", "Italie", "Allemagne de l'Ouest", "Angleterre"], a: 2 }
    ],
    medium: [
        { q: "Qui détient le record du plus grand nombre de buts marqués en un SEUL tournoi ?", o: ["Just Fontaine", "Müller", "Klose", "Ronaldo"], a: 0 },
        { q: "Combien de buts Just Fontaine a-t-il marqués en 1958 ?", o: ["10", "11", "13", "15"], a: 2 },
        { q: "Quel pays a atteint la finale 1950 contre le Brésil (Maracanazo) ?", o: ["Uruguay", "Argentine", "Espagne", "Suède"], a: 0 },
        { q: "Qui l'Allemagne a-t-elle battu 7-1 en 2014 ?", o: ["Argentine", "Brésil", "France", "Portugal"], a: 1 },
        { q: "Quel joueur a marqué le but 'du siècle' en 1986 ?", o: ["Platini", "Lineker", "Maradona", "Zico"], a: 2 },
        { q: "Quelle équipe a perdu 3 finales sans jamais gagner (1974, 1978, 2010) ?", o: ["Hongrie", "Pays-Bas", "République Tchèque", "France"], a: 1 },
        { q: "Qui était le capitaine de la France en 1998 ?", o: ["Deschamps", "Blanc", "Zidane", "Desailly"], a: 0 },
        { q: "Quel pays a organisé la Coupe du Monde 1962 ?", o: ["Chili", "Suède", "Suisse", "Angleterre"], a: 0 },
        { q: "Quel joueur détient le record de buts TOTAL en Coupe du Monde (16 buts) ?", o: ["Ronaldo (Brésil)", "Müller", "Klose", "Pelé"], a: 2 },
        { q: "Qui a gagné le titre de meilleur jeune joueur en 2018 ?", o: ["Pogba", "Varane", "Mbappé", "Pavard"], a: 2 },
        { q: "Quel pays a gagné le Mondial 1966 ?", o: ["Allemagne de l'Ouest", "Angleterre", "Portugal", "URSS"], a: 1 },
        { q: "Quel joueur français a pris un carton rouge en finale 2006 ?", o: ["Vieira", "Zidane", "Henry", "Ribéry"], a: 1 },
        { q: "Quel pays a accueilli la Coupe du Monde pour la première fois en Asie (2002) ?", o: ["Chine", "Japon / Corée du Sud", "Qatar", "Thaïlande"], a: 1 },
        { q: "Contre quelle équipe Zinédine Zidane a-t-il marqué ses 2 buts en 1998 ?", o: ["Croatie", "Brésil", "Italie", "Danemark"], a: 1 },
        { q: "Qui a éliminé la France en 1982 au terme d'un match dramatique ?", o: ["Brésil", "Allemagne", "Italie", "Pologne"], a: 1 },
        { q: "Quel joueur brésilien a dû déclarer forfait juste avant la finale 1998 (mais a joué) ?", o: ["Rivaldo", "Ronaldo", "Romario", "Bebeto"], a: 1 },
        { q: "Quel pays a fini 3ème du Mondial 2022 ?", o: ["Maroc", "Croatie", "France", "Brésil"], a: 1 },
        { q: "En quelle année le tournoi a-t-1 été organisé au Mexique pour la première fois ?", o: ["1970", "1986", "1966", "1994"], a: 0 },
        { q: "Qui a marqué le 'but de la main' en 1986 ?", o: ["Kempes", "Maradona", "Valdano", "Burruchaga"], a: 1 },
        { q: "Quelle équipe africaine a été la première à atteindre les demi-finales (2022) ?", o: ["Sénégal", "Ghana", "Maroc", "Cameroun"], a: 2 },
        { q: "Qui l'Espagne a-t-elle battu en finale en 2010 ?", o: ["Allemagne", "Pays-Bas", "Uruguay", "Italie"], a: 1 },
        { q: "Quel pays détient le record de finales perdues ?", o: ["Allemagne", "Argentine", "Pays-Bas", "France"], a: 0 },
        { q: "Quel joueur argentin a marqué deux buts en finale 1978 ?", o: ["Kempes", "Luque", "Passarella", "Ardiles"], a: 0 },
        { q: "Qui a remporté le Ballon d'Or (meilleur joueur) en 2014 ?", o: ["Müller", "James Rodríguez", "Messi", "Neuer"], a: 2 },
        { q: "Combien de titres mondiaux a remporté l'Italie ?", o: ["2", "3", "4", "5"], a: 2 },
        { q: "Quel est le score de la finale 2014 après prolongations ?", o: ["0-0", "1-0", "2-1", "1-1"], a: 1 },
        { q: "Qui a marqué le penalty de la victoire pour l'Italie en 2006 ?", o: ["Pirlo", "Grosso", "Cannavaro", "Del Piero"], a: 1 },
        { q: "Quel pays a organisé le Mondial 1958 ?", o: ["Suisse", "Suède", "Chili", "Brésil"], a: 1 },
        { q: "Quel joueur est le plus vieux buteur de l'histoire du Mondial ?", o: ["Milla", "Ronaldo", "Messi", "Klose"], a: 0 },
        { q: "Quel pays a boycotté la première Coupe du Monde en 1930 ?", o: [" Angleterre", "Allemagne", "Italie", "Beaucoup d'équipes européennes"], a: 3 },
        { q: "En quelle année la Coupe du Monde a-t-elle été interrompue à cause de la guerre ?", o: ["1938 & 1942", "1942 & 1946", "1946 & 1950", "1934 & 1938"], a: 1 },
        { q: "Quel pays a gagné le Mondial 1938 ?", o: ["Italie", "France", "B rèsil", "Hongrie"], a: 0 },
        { q: "Qui a marqué le triplé en finale 1966 ?", o: ["Bobby Charlton", "Geoff Hurst", "Pelé", "Eusebio"], a: 1 },
        { q: "Quel joueur brésilien a gagné 3 Coupes du Monde ?", o: ["Ronaldo", "Pelé", "Cafu", "Zagallo"], a: 1 },
        { q: "Quelle équipe est surnommée 'La Céleste' ?", o: ["Argentine", "Italie", "Uruguay", "Grèce"], a: 2 },
        { q: "Quel pays a accueilli le Mondial 1974 ?", o: ["Mexique", "Allemagne de l'Ouest", "Argentine", "Yougoslavie"], a: 1 },
        { q: "Qui était le sélectionneur de l'Allemagne en 2014 ?", o: ["Klinsmann", "Löw", "Flick", "Heynckes"], a: 1 },
        { q: "Qui a marqué le but décisif en finale 2014 ?", o: ["Götze", "Schürrle", "Klose", "Müller"], a: 0 },
        { q: "Quel pays a fini 4ème en 2022 ?", o: ["Croatie", "Maroc", "Brésil", "Pays-Bas"], a: 1 },
        { q: "Combien de fois la France a-t-elle atteint la finale ?", o: ["2", "3", "4", "5"], a: 2 },
        { q: "Quel joueur a marqué contre son camp en 1994 (et a été assassiné au pays) ?", o: ["Escobar", "Valderrama", "Asprilla", "Rincon"], a: 0 },
        { q: "Qui l'Argentine a-t-elle battu en finale en 1986 ?", o: ["RFA", "Italie", "Belgique", "Angleterre"], a: 0 },
        { q: "Quel pays a organisé le tournoi en 1954 ?", o: ["Autriche", "Suisse", "Suède", "Brésil"], a: 1 },
        { q: "Qui est surnommé 'La Panthère Noire' ?", o: ["Pelé", "Eusebio", "Roger Milla", "Weah"], a: 1 },
        { q: "Quel pays a accueilli le Mondial 1990 ?", o: ["Espagne", "Italie", "Mexique", "USA"], a: 1 },
        { q: "Quelle équipe a gagné le Mondial 1950 ?", o: ["Brésil", "Uruguay", "Espagne", "Suède"], a: 1 },
        { q: "Quel gardien a arrêté 4 tirs au but contre la France en finale 2022 ?", o: ["Martinez", "Lloris", "Bounou", "Livakovic"], a: 0 },
        { q: "Qui a gagné le Mondial 1970 ?", o: ["Italie", "Brésil", "Uruguay", "Pérou"], a: 1 },
        { q: "Quel pays a organisé le tournoi en 1934 ?", o: ["Italie", "Uruguay", "Allemagne", "France"], a: 0 },
        { q: "Qui était le meilleur buteur du Mondial 2002 ?", o: ["Ronaldo", "Klose", "Rivaldo", "Tomasson"], a: 0 }
    ],
    hard: [
        { q: "Quel pays est le seul à avoir disputé TOUTES les phases finales ?", o: ["Allemagne", "Italie", "Argentine", "Brésil"], a: 3 },
        { q: "En quelle année l'Uruguay a-t-il gagné son deuxième et dernier titre ?", o: ["1930", "1950", "1934", "1954"], a: 1 },
        { q: "Qui a marqué le premier but de l'histoire de la Coupe du Monde ?", o: ["Lucien Laurent", "Stabile", "Vidal", "Meazza"], a: 0 },
        { q: "Quel arbitre a officié lors de la finale 1998 ?", o: ["Collina", "Said Belqola", "Horoald", "Dallas"], a: 1 },
        { q: "Quel pays africain a été le premier à se qualifier pour un Mondial (1934) ?", o: ["Maroc", "Égypte", "Tunisie", "Nigeria"], a: 1 },
        { q: "Quel gardien détient le record du plus d'arrêts en un match (16 arrêts contre la Belgique) ?", o: ["Howard", "Ochoa", "Navas", "Courtois"], a: 0 },
        { q: "Quel joueur a été expulsé en finale 1990 ?", o: ["Monzon", "Maradona", "Voller", "Klinsmann"], a: 0 },
        { q: "Qui a gagné le prix du meilleur jeune en 2006 ?", o: ["Messi", "Ronaldo", "Podolski", "Rooney"], a: 2 },
        { q: "Quelle équipe a marqué le plus de buts en UN SEUL tournoi (27 buts en 1954) ?", o: ["Brésil", "Hongrie", "Allemagne", "France"], a: 1 },
        { q: "Quel joueur détient le record de cartons rouges en Coupe du Monde (2) ?", o: ["Zidane & Rigobert Song", "Ramos & Pepe", "Gattuso & Keane", "Suarez & Neymar"], a: 0 },
        { q: "Quel pays a organisé le Mondial 1938 ?", o: ["Suisse", "France", "Italie", "Allemagne"], a: 1 },
        { q: "Qui a marqué le but égalisateur des Pays-Bas à la 90+11 en 2022 contre l'Argentine ?", o: ["Weghorst", "Gakpo", "Depay", "De Jong"], a: 0 },
        { q: "Quel gardien soviétique est le seul à avoir eu le Ballon d'Or France Football ?", o: ["Yashin", "Dasaev", "Akinfeev", "Chilavert"], a: 0 },
        { q: "Quel joueur détient le record de minutes jouées en Coupe du Monde ?", o: ["Maldini", "Messi", "Matthäus", "Ronaldo"], a: 1 },
        { q: "En quelle année la règle du 'But en Or' a-t-elle été utilisée pour la première fois ?", o: ["1994", "1998", "2002", "1990"], a: 1 },
        { q: "Quel pays a accueilli le Mondial 1986 suite au désistement de la Colombie ?", o: ["USA", "Mexique", "Canada", "Brésil"], a: 1 },
        { q: "Contre quel pays Pelé a-t-il marqué son premier but en Mondial ?", o: ["Pays de Galles", "France", "Suède", "URSS"], a: 0 },
        { q: "Quel est le nom de l'entraîneur qui a gagné la Coupe du Monde en tant que joueur et entraîneur (le 1er) ?", o: ["Zagallo", "Beckenbauer", "Deschamps", "Cruyff"], a: 0 },
        { q: "Combien d'équipes ont gagné au moins une fois la Coupe du Monde ?", o: ["6", "7", "8", "9"], a: 2 },
        { q: "Quel pays a organisé le mondial 1962 ?", o: ["Chili", "Suède", "Suisse", "Mexique"], a: 0 },
        { q: "Quel gardien a gardé sa cage inviolée pendant 517 minutes consécutives (record) ?", o: ["Zenga", "Casillas", "Buffon", "Neuer"], a: 0 },
        { q: "Qui est le meilleur buteur africain de l'histoire du Mondial ?", o: ["Gyan", "Milla", "Eto'o", "Drogba"], a: 0 },
        { q: "En quelle année est apparu le premier carton rouge en Coupe du Monde ?", o: ["1970", "1974", "1966", "1978"], a: 1 },
        { q: "Quel pays a perdu contre l'Australie 31-0 lors des qualifications 2002 ?", o: ["Samoa Américaines", "Tonga", "Fidji", "Cook"], a: 0 },
        { q: "Quel joueur allemand a disputé 5 phases finales (record partagé) ?", o: ["Klose", "Matthäus", "Müller", "Lahm"], a: 1 },
        { q: "Qui a arbitré la finale 2010 (record de cartons jaunes en finale) ?", o: ["Howard Webb", "Collina", "Nishimura", "Rizzoli"], a: 0 },
        { q: "Contre quel pays Zinédine Zidane a-t-il marqué sur penalty en 2006 (Demi-finale) ?", o: ["Portugal", "Italie", "Espagne", "Brésil"], a: 0 },
        { q: "Quel pays a fini 3 ème en 1994 ?", o: ["Suède", "Bulgarie", "Italie", "Brésil"], a: 0 },
        { q: "Qui était le capitaine du Brésil en 2002 ?", o: ["Cafu", "Lucio", "Ronaldo", "Ronaldinho"], a: 0 },
        { q: "Quel pays est le seul organisateur à avoir été éliminé au premier tour (jusqu'en 2022) ?", o: ["Afrique du Sud & Qatar", "Afrique du Sud seulement", "Qatar seulement", "Japon"], a: 0 },
        { q: "Quel joueur détient le record de sélections avec l'Arabie Saoudite en Mondial ?", o: ["Al-Jaber", "Al-Deayea", "Al-Owairan", "Al-Muwallad"], a: 0 },
        { q: "Quel est le score le plus large en finale ?", o: ["5-2", "4-2", "3-0", "4-1"], a: 0 },
        { q: "Qui était l'entraîneur de l'Espagne en 2010 ?", o: ["Aragonés", "Del Bosque", "Guardiola", "Emery"], a: 1 },
        { q: "Quel pays a organisé le Mondial 1930 ?", o: ["Uruguay", "Brésil", "Argentine", "France"], a: 0 },
        { q: "Quelle nation a gagné la 'petite finale' (3ème place) en 1998 ?", o: ["Pays-Bas", "Croatie", "Brésil", "France"], a: 1 },
        { q: "Qui a marqué le but de la victoire en finale 1974 ?", o: ["Gerd Müller", "Paul Breitner", "Johan Cruyff", "Neeskens"], a: 0 },
        { q: "Quel joueur italien a raté le dernier penalty en 1994 ?", o: ["Baggio", "Baresi", "Albertini", "Massaro"], a: 0 },
        { q: "Quel pays a accueilli la Coupe du Monde 1950 ?", o: ["Brésil", "Uruguay", "Suisse", "Suède"], a: 0 },
        { q: "Qui était le meilleur buteur en 1994 (Ex-aequo) ?", o: ["Salenko & Stoichkov", "Romario & Baggio", "Klinsmann & Batistuta", "Larsson & Dahlin"], a: 0 },
        { q: "Combien de finales ont été décidées aux tirs au but ?", o: ["1", "2", "3", "4"], a: 2 },
        { q: "Quel pays a organisé le premier Mondial en Afrique ?", o: ["Afrique du Sud", "Maroc", "Égypte", "Tunisie"], a: 0 },
        { q: "Quel joueur français a marqué contre l'Arabie Saoudite en 1998 avant d'être expulsé ?", o: ["Zidane", "Henry", "Trezeguet", "Dugarry"], a: 0 },
        { q: "Qui a marqué le 'but de l'ombre' (Phantom goal) de 1966 ?", o: ["Hurst", "Peters", "Charlton", "Hunt"], a: 0 },
        { q: "Quel pays a fini 3 ème en 1998 ?", o: ["Croatie", "Pays-Bas", "Brésil", "France"], a: 0 },
        { q: "Quel joueur détient le record d'apparitions en tant que CAPITAINE en Coupe du Monde ?", o: ["Maradona", "Messi", "Matthäus", "Cafu"], a: 1 },
        { q: "Quel pays a accueilli le Mondial 1978 ?", o: ["Mexique", "Argentine", "Brésil", "Espagne"], a: 1 },
        { q: "Contre quel pays Roger Milla a-t-il marqué à 42 ans en 1994 ?", o: ["Russie", "Brésil", "Cameroun", "Suède"], a: 0 },
        { q: "En quelle année est apparue l'assistance vidéo (VAR) en Mondial ?", o: ["2014", "2018", "2022", "2010"], a: 1 },
        { q: "Quel pays a organisé le Mondial 1954 ?", o: ["Suisse", "Autriche", "Suède", "Brésil"], a: 0 },
        { q: "Qui a marqué le but égalisateur de l'Angleterre en finale 1966 à la dernière minute ?", o: ["Weber (Allemagne)", "Hurst", "Charlton", "Seeler"], a: 0 }
    ]
};
