// Sofascore stats via RapidAPI for WC2026 players
// Generated 2026-06-01T12:08:01.085Z — 25/25 found
const SOFASCORE_V2 = {
  "rpmatjko0": {
    "id": "rpmatjko0",
    "name": "Matěj Kovář",
    "sofascoreId": 927366,
    "sofascoreSlug": "matej-kovar",
    "photo": "https://img.sofascore.com/api/v1/player/927366/image",
    "position": "G",
    "team": "PSV Eindhoven",
    "country": "Czechia",
    "jerseyNumber": "32",
    "seasons": [
      {
        "tournament": "VriendenLoterij Eredivisie",
        "season": "25/26",
        "apps": 31,
        "goals": 0,
        "assists": 0,
        "minutes": 2790,
        "rating": 7.08,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 2,
        "xG": null,
        "xA": 0.12
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 9,
        "goals": 0,
        "assists": 0,
        "minutes": 870,
        "rating": 7.03,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 8,
        "goals": 0,
        "assists": 0,
        "minutes": 720,
        "rating": 6.8,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 1,
        "xG": null,
        "xA": 0.01
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 6,
        "goals": 0,
        "assists": 0,
        "minutes": 540,
        "rating": 6.65,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.01
      },
      {
        "tournament": "Bundesliga",
        "season": "24/25",
        "apps": 5,
        "goals": 0,
        "assists": 0,
        "minutes": 450,
        "rating": 7,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.01
      },
      {
        "tournament": "Bundesliga",
        "season": "23/24",
        "apps": 1,
        "goals": 0,
        "assists": 0,
        "minutes": 90,
        "rating": 7.5,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0
      }
    ],
    "transfers": [
      {
        "from": "Bayer 04 Leverkusen",
        "to": "PSV Eindhoven",
        "fee": 5000000,
        "year": null
      },
      {
        "from": "PSV Eindhoven",
        "to": "Bayer 04 Leverkusen",
        "fee": null,
        "year": null
      },
      {
        "from": "Bayer 04 Leverkusen",
        "to": "PSV Eindhoven",
        "fee": 5000000,
        "year": null
      },
      {
        "from": "Bayer 04 Leverkusen",
        "to": "PSV Eindhoven",
        "fee": null,
        "year": null
      },
      {
        "from": "Manchester United",
        "to": "Bayer 04 Leverkusen",
        "fee": 5000000,
        "year": null
      },
      {
        "from": "AC Sparta Praha",
        "to": "Manchester United",
        "fee": null,
        "year": null
      },
      {
        "from": "Manchester United",
        "to": "AC Sparta Praha",
        "fee": null,
        "year": null
      },
      {
        "from": "Manchester United U21",
        "to": "Manchester United",
        "fee": null,
        "year": null
      },
      {
        "from": "Manchester United U21",
        "to": "Burton Albion",
        "fee": null,
        "year": null
      },
      {
        "from": "Manchester United U21",
        "to": "Swindon Town",
        "fee": null,
        "year": null
      }
    ]
  },
  "rpjindic0": {
    "id": "rpjindic0",
    "name": "Jindřich Staněk",
    "sofascoreId": 280601,
    "sofascoreSlug": "jindrich-stanek",
    "photo": "https://img.sofascore.com/api/v1/player/280601/image",
    "position": "G",
    "team": "SK Slavia Praha",
    "country": "Czechia",
    "jerseyNumber": "36",
    "seasons": [
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 1,
        "goals": 0,
        "assists": 0,
        "minutes": 90,
        "rating": 8.3,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2022",
        "apps": 0,
        "goals": 0,
        "assists": 0,
        "minutes": 76,
        "rating": 6.6,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 6,
        "goals": 0,
        "assists": 0,
        "minutes": 540,
        "rating": 7.08,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.01
      },
      {
        "tournament": "UEFA Champions League",
        "season": "22/23",
        "apps": 5,
        "goals": 0,
        "assists": 0,
        "minutes": 450,
        "rating": 6.44,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.01
      },
      {
        "tournament": "UEFA Europa League",
        "season": "23/24",
        "apps": 2,
        "goals": 0,
        "assists": 0,
        "minutes": 180,
        "rating": 6.45,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0
      }
    ],
    "transfers": [
      {
        "from": "FC Viktoria Plzeň",
        "to": "SK Slavia Praha",
        "fee": 1000000,
        "year": null
      },
      {
        "from": "SK Dynamo České Budějovice",
        "to": "FC Viktoria Plzeň",
        "fee": null,
        "year": null
      },
      {
        "from": "FC Viktoria Plzeň",
        "to": "SK Dynamo České Budějovice",
        "fee": null,
        "year": null
      },
      {
        "from": "SK Dynamo České Budějovice",
        "to": "FC Viktoria Plzeň",
        "fee": null,
        "year": null
      },
      {
        "from": "SK Dynamo Ceske Budejovice B",
        "to": "SK Dynamo České Budějovice",
        "fee": null,
        "year": null
      },
      {
        "from": "FK Trebic",
        "to": "SK Dynamo Ceske Budejovice B",
        "fee": null,
        "year": null
      },
      {
        "from": "SK Dynamo Ceske Budejovice B",
        "to": "FK Trebic",
        "fee": null,
        "year": null
      },
      {
        "from": "Everton U21",
        "to": "SK Dynamo Ceske Budejovice B",
        "fee": null,
        "year": null
      },
      {
        "from": "Everton U21",
        "to": "Hyde United",
        "fee": null,
        "year": null
      }
    ]
  },
  "rplukhor0": {
    "id": "rplukhor0",
    "name": "Lukáš Horníček",
    "sofascoreId": 963744,
    "sofascoreSlug": "lukas-hornicek",
    "photo": "https://img.sofascore.com/api/v1/player/963744/image",
    "position": "G",
    "team": "Sporting Braga",
    "country": "Czechia",
    "jerseyNumber": "1",
    "seasons": [
      {
        "tournament": "UEFA Europa League",
        "season": "25/26",
        "apps": 14,
        "goals": 0,
        "assists": 0,
        "minutes": 1260,
        "rating": 7.06,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.05
      },
      {
        "tournament": "UEFA Europa League",
        "season": "24/25",
        "apps": 3,
        "goals": 0,
        "assists": 0,
        "minutes": 290,
        "rating": 7.22,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0
      }
    ],
    "transfers": [
      {
        "from": "SC Braga B",
        "to": "Sporting Braga",
        "fee": null,
        "year": null
      },
      {
        "from": "SC Braga U23",
        "to": "SC Braga B",
        "fee": null,
        "year": null
      },
      {
        "from": "SC Braga U19",
        "to": "FK Pardubice",
        "fee": null,
        "year": null
      },
      {
        "from": "FK Pardubice U19",
        "to": "FK Pardubice",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr2": {
    "id": "fr2",
    "name": "Brice SAMBA",
    "sofascoreId": 164055,
    "sofascoreSlug": "brice-samba",
    "photo": "https://img.sofascore.com/api/v1/player/164055/image",
    "position": "G",
    "team": "Stade Rennais",
    "country": "France",
    "jerseyNumber": "30",
    "seasons": [
      {
        "tournament": "Ligue 1",
        "season": "25/26",
        "apps": 32,
        "goals": 0,
        "assists": 0,
        "minutes": 2880,
        "rating": 6.95,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 5,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 2,
        "xG": null,
        "xA": 0.07
      },
      {
        "tournament": "Ligue 1",
        "season": "24/25",
        "apps": 32,
        "goals": 0,
        "assists": 0,
        "minutes": 2879,
        "rating": 7.22,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 4,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.08
      },
      {
        "tournament": "UEFA Europa League",
        "season": "23/24",
        "apps": 2,
        "goals": 0,
        "assists": 0,
        "minutes": 210,
        "rating": 7.7,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0
      },
      {
        "tournament": "UEFA Champions League",
        "season": "23/24",
        "apps": 6,
        "goals": 0,
        "assists": 0,
        "minutes": 540,
        "rating": 7.08,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.01
      }
    ],
    "transfers": [
      {
        "from": "RC Lens",
        "to": "Stade Rennais",
        "fee": 14000000,
        "year": null
      },
      {
        "from": "Nottingham Forest",
        "to": "RC Lens",
        "fee": 5000000,
        "year": null
      },
      {
        "from": "Caen",
        "to": "Nottingham Forest",
        "fee": 2100000,
        "year": null
      },
      {
        "from": "Olympique de Marseille",
        "to": "Caen",
        "fee": null,
        "year": null
      },
      {
        "from": "Nancy",
        "to": "Olympique de Marseille",
        "fee": null,
        "year": null
      },
      {
        "from": "Olympique de Marseille",
        "to": "Nancy",
        "fee": null,
        "year": null
      },
      {
        "from": "Le Havre",
        "to": "Olympique de Marseille",
        "fee": 400000,
        "year": null
      },
      {
        "from": "Le Havre U19",
        "to": "Le Havre",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr1": {
    "id": "fr1",
    "name": "Mike MAIGNAN",
    "sofascoreId": 191210,
    "sofascoreSlug": "mike-maignan",
    "photo": "https://img.sofascore.com/api/v1/player/191210/image",
    "position": "G",
    "team": "AC Milan",
    "country": "France",
    "jerseyNumber": "16",
    "seasons": [
      {
        "tournament": "Serie A",
        "season": "25/26",
        "apps": 37,
        "goals": 0,
        "assists": 0,
        "minutes": 3296,
        "rating": 7.23,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 4,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.03
      },
      {
        "tournament": "Serie A",
        "season": "24/25",
        "apps": 37,
        "goals": 0,
        "assists": 0,
        "minutes": 3295,
        "rating": 7.08,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 5,
        "xG": null,
        "xA": 0.21
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 5,
        "goals": 0,
        "assists": 0,
        "minutes": 450,
        "rating": 6.66,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 10,
        "goals": 0,
        "assists": 0,
        "minutes": 861,
        "rating": 7.26,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.02
      },
      {
        "tournament": "UEFA Champions League",
        "season": "23/24",
        "apps": 6,
        "goals": 0,
        "assists": 0,
        "minutes": 531,
        "rating": 7.27,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.05
      },
      {
        "tournament": "UEFA Europa League",
        "season": "23/24",
        "apps": 6,
        "goals": 0,
        "assists": 0,
        "minutes": 471,
        "rating": 6.92,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0
      },
      {
        "tournament": "UEFA Europa League",
        "season": "20/21",
        "apps": 8,
        "goals": 0,
        "assists": 0,
        "minutes": 720,
        "rating": 6.6,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Ligue 1",
        "season": "20/21",
        "apps": 38,
        "goals": 0,
        "assists": 0,
        "minutes": 3420,
        "rating": 7.08,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 1,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "Lille",
        "to": "AC Milan",
        "fee": 16399999,
        "year": null
      },
      {
        "from": "Paris Saint-Germain",
        "to": "Lille",
        "fee": 1000000,
        "year": null
      },
      {
        "from": "Paris Saint-Germain 2",
        "to": "Paris Saint-Germain",
        "fee": null,
        "year": null
      },
      {
        "from": "Paris Saint-Germain U19",
        "to": "Paris Saint-Germain 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr3": {
    "id": "fr3",
    "name": "Robin RISSER",
    "sofascoreId": 1387161,
    "sofascoreSlug": "robin-risser",
    "photo": "https://img.sofascore.com/api/v1/player/1387161/image",
    "position": "G",
    "team": "RC Lens",
    "country": "France",
    "jerseyNumber": "40",
    "seasons": [
      {
        "tournament": "Ligue 1",
        "season": "25/26",
        "apps": 33,
        "goals": 0,
        "assists": 1,
        "minutes": 2970,
        "rating": 7.06,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 2,
        "xG": null,
        "xA": 0.02
      }
    ],
    "transfers": [
      {
        "from": "RC Strasbourg",
        "to": "RC Lens",
        "fee": 3000000,
        "year": null
      },
      {
        "from": "Red Star FC",
        "to": "RC Strasbourg",
        "fee": null,
        "year": null
      },
      {
        "from": "RC Strasbourg",
        "to": "Red Star FC",
        "fee": null,
        "year": null
      },
      {
        "from": "Dijon",
        "to": "RC Strasbourg",
        "fee": null,
        "year": null
      },
      {
        "from": "RC Strasbourg",
        "to": "Dijon",
        "fee": null,
        "year": null
      },
      {
        "from": "Strasbourg U19",
        "to": "RC Strasbourg",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr14": {
    "id": "fr14",
    "name": "Malo GUSTO",
    "sofascoreId": 996958,
    "sofascoreSlug": "gusto-malo",
    "photo": "https://img.sofascore.com/api/v1/player/996958/image",
    "position": "D",
    "team": "Chelsea",
    "country": "France",
    "jerseyNumber": "27",
    "seasons": [
      {
        "tournament": "Premier League",
        "season": "25/26",
        "apps": 26,
        "goals": 2,
        "assists": 3,
        "minutes": 2267,
        "rating": 6.64,
        "shots": 12,
        "shotsOnTarget": 6,
        "yellowCards": 3,
        "redCards": 1,
        "dribbles": 13,
        "keyPasses": 28,
        "xG": 1.56,
        "xA": 2.99
      },
      {
        "tournament": "Premier League",
        "season": "24/25",
        "apps": 19,
        "goals": 0,
        "assists": 1,
        "minutes": 1876,
        "rating": 6.85,
        "shots": 22,
        "shotsOnTarget": 5,
        "yellowCards": 4,
        "redCards": 0,
        "dribbles": 4,
        "keyPasses": 22,
        "xG": 1.7,
        "xA": 1.94
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 2,
        "goals": 0,
        "assists": 2,
        "minutes": 209,
        "rating": 7.67,
        "shots": 2,
        "shotsOnTarget": 1,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 5,
        "keyPasses": 2,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 6,
        "goals": 1,
        "assists": 1,
        "minutes": 476,
        "rating": 6.64,
        "shots": 5,
        "shotsOnTarget": 1,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 4,
        "keyPasses": 5,
        "xG": 0.37,
        "xA": 0.51
      },
      {
        "tournament": "Ligue 1",
        "season": "22/23",
        "apps": 19,
        "goals": 0,
        "assists": 1,
        "minutes": 1606,
        "rating": 6.95,
        "shots": 7,
        "shotsOnTarget": 3,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 20,
        "keyPasses": 24,
        "xG": 0.41,
        "xA": 4.11
      },
      {
        "tournament": "Ligue 1",
        "season": "21/22",
        "apps": 21,
        "goals": 0,
        "assists": 4,
        "minutes": 1893,
        "rating": 6.86,
        "shots": 11,
        "shotsOnTarget": 0,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 19,
        "keyPasses": 25,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Europa League",
        "season": "21/22",
        "apps": 5,
        "goals": 0,
        "assists": 1,
        "minutes": 458,
        "rating": 6.64,
        "shots": 2,
        "shotsOnTarget": 1,
        "yellowCards": 0,
        "redCards": 1,
        "dribbles": 4,
        "keyPasses": 5,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "Olympique Lyonnais",
        "to": "Chelsea",
        "fee": null,
        "year": null
      },
      {
        "from": "Chelsea",
        "to": "Olympique Lyonnais",
        "fee": null,
        "year": null
      },
      {
        "from": "Olympique Lyonnais",
        "to": "Chelsea",
        "fee": 30000000,
        "year": null
      },
      {
        "from": "Olympique Lyonnais 2",
        "to": "Olympique Lyonnais",
        "fee": null,
        "year": null
      },
      {
        "from": "Olympique Lyon U19",
        "to": "Olympique Lyonnais 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr10": {
    "id": "fr10",
    "name": "Lucas DIGNE",
    "sofascoreId": 96538,
    "sofascoreSlug": "lucas-digne",
    "photo": "https://img.sofascore.com/api/v1/player/96538/image",
    "position": "D",
    "team": "Aston Villa",
    "country": "France",
    "jerseyNumber": "12",
    "seasons": [
      {
        "tournament": "Premier League",
        "season": "25/26",
        "apps": 21,
        "goals": 0,
        "assists": 6,
        "minutes": 1866,
        "rating": 6.76,
        "shots": 14,
        "shotsOnTarget": 5,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 4,
        "keyPasses": 26,
        "xG": 0.72,
        "xA": 3.26
      },
      {
        "tournament": "Premier League",
        "season": "24/25",
        "apps": 28,
        "goals": 0,
        "assists": 4,
        "minutes": 2358,
        "rating": 6.97,
        "shots": 13,
        "shotsOnTarget": 3,
        "yellowCards": 4,
        "redCards": 0,
        "dribbles": 9,
        "keyPasses": 36,
        "xG": 0.8,
        "xA": 4.01
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 3,
        "goals": 0,
        "assists": 1,
        "minutes": 270,
        "rating": 7.47,
        "shots": 3,
        "shotsOnTarget": 1,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 4,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2022",
        "apps": 4,
        "goals": 0,
        "assists": 1,
        "minutes": 360,
        "rating": 7.03,
        "shots": 1,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 6,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Europa League",
        "season": "25/26",
        "apps": 9,
        "goals": 0,
        "assists": 1,
        "minutes": 817,
        "rating": 6.75,
        "shots": 5,
        "shotsOnTarget": 1,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 6,
        "xG": 0.28,
        "xA": 0.62
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 9,
        "goals": 0,
        "assists": 0,
        "minutes": 748,
        "rating": 6.83,
        "shots": 4,
        "shotsOnTarget": 2,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 9,
        "xG": 0.35,
        "xA": 1.01
      },
      {
        "tournament": "UEFA Champions League",
        "season": "17/18",
        "apps": 3,
        "goals": 1,
        "assists": 0,
        "minutes": 270,
        "rating": 7.4,
        "shots": 1,
        "shotsOnTarget": 1,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 2,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Copa del Rey",
        "season": "17/18",
        "apps": 4,
        "goals": 0,
        "assists": 0,
        "minutes": 353,
        "rating": null,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "Everton",
        "to": "Aston Villa",
        "fee": 30000000,
        "year": null
      },
      {
        "from": "FC Barcelona",
        "to": "Everton",
        "fee": 20200000,
        "year": null
      },
      {
        "from": "Paris Saint-Germain",
        "to": "FC Barcelona",
        "fee": 16500000,
        "year": null
      },
      {
        "from": "AS Roma",
        "to": "Paris Saint-Germain",
        "fee": null,
        "year": null
      },
      {
        "from": "Paris Saint-Germain",
        "to": "AS Roma",
        "fee": null,
        "year": null
      },
      {
        "from": "Lille",
        "to": "Paris Saint-Germain",
        "fee": 15000000,
        "year": null
      },
      {
        "from": "LOSC Lille 2",
        "to": "Lille",
        "fee": null,
        "year": null
      },
      {
        "from": "Lille U19",
        "to": "LOSC Lille 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr5": {
    "id": "fr5",
    "name": "Dayot UPAMECANO",
    "sofascoreId": 798583,
    "sofascoreSlug": "dayot-upamecano",
    "photo": "https://img.sofascore.com/api/v1/player/798583/image",
    "position": "D",
    "team": "FC Bayern München",
    "country": "France",
    "jerseyNumber": "2",
    "seasons": [
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 5,
        "goals": 0,
        "assists": 0,
        "minutes": 450,
        "rating": 7.26,
        "shots": 1,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 1,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2022",
        "apps": 2,
        "goals": 0,
        "assists": 0,
        "minutes": 180,
        "rating": 7.1,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Bundesliga",
        "season": "25/26",
        "apps": 21,
        "goals": 1,
        "assists": 1,
        "minutes": 1797,
        "rating": 7.16,
        "shots": 8,
        "shotsOnTarget": 2,
        "yellowCards": 4,
        "redCards": 0,
        "dribbles": 4,
        "keyPasses": 11,
        "xG": 1.03,
        "xA": 1.62
      },
      {
        "tournament": "Bundesliga",
        "season": "24/25",
        "apps": 20,
        "goals": 2,
        "assists": 0,
        "minutes": 1761,
        "rating": 7.37,
        "shots": 13,
        "shotsOnTarget": 6,
        "yellowCards": 6,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 7,
        "xG": 1.21,
        "xA": 1.2
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 12,
        "goals": 1,
        "assists": 2,
        "minutes": 1013,
        "rating": 6.78,
        "shots": 9,
        "shotsOnTarget": 4,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 5,
        "xG": 1.47,
        "xA": 0.62
      },
      {
        "tournament": "UEFA Europa League",
        "season": "18/19",
        "apps": 4,
        "goals": 0,
        "assists": 0,
        "minutes": 360,
        "rating": 7.13,
        "shots": 4,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 1,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Europa League",
        "season": "17/18",
        "apps": 6,
        "goals": 0,
        "assists": 0,
        "minutes": 516,
        "rating": 6.92,
        "shots": 3,
        "shotsOnTarget": 2,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 4,
        "keyPasses": 2,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "RB Leipzig",
        "to": "FC Bayern München",
        "fee": 42500000,
        "year": null
      },
      {
        "from": "Red Bull Salzburg",
        "to": "RB Leipzig",
        "fee": 18500000,
        "year": null
      },
      {
        "from": "Valenciennes U19",
        "to": "Red Bull Salzburg",
        "fee": 2200000,
        "year": null
      }
    ]
  },
  "fr6": {
    "id": "fr6",
    "name": "Jules KOUNDÉ",
    "sofascoreId": 827212,
    "sofascoreSlug": "jules-kounde",
    "photo": "https://img.sofascore.com/api/v1/player/827212/image",
    "position": "D",
    "team": "FC Barcelona",
    "country": "France",
    "jerseyNumber": "23",
    "seasons": [
      {
        "tournament": "LaLiga",
        "season": "25/26",
        "apps": 24,
        "goals": 1,
        "assists": 3,
        "minutes": 2269,
        "rating": 6.9,
        "shots": 14,
        "shotsOnTarget": 4,
        "yellowCards": 6,
        "redCards": 0,
        "dribbles": 21,
        "keyPasses": 23,
        "xG": 1.66,
        "xA": 3.39
      },
      {
        "tournament": "LaLiga",
        "season": "24/25",
        "apps": 29,
        "goals": 2,
        "assists": 3,
        "minutes": 2606,
        "rating": 7.17,
        "shots": 18,
        "shotsOnTarget": 6,
        "yellowCards": 4,
        "redCards": 0,
        "dribbles": 22,
        "keyPasses": 32,
        "xG": 1.81,
        "xA": 3.79
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 4,
        "goals": 0,
        "assists": 0,
        "minutes": 331,
        "rating": 7.28,
        "shots": 3,
        "shotsOnTarget": 1,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 4,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Copa del Rey",
        "season": "25/26",
        "apps": 3,
        "goals": 0,
        "assists": 0,
        "minutes": 220,
        "rating": null,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Copa del Rey",
        "season": "24/25",
        "apps": 6,
        "goals": 2,
        "assists": 1,
        "minutes": 531,
        "rating": null,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 10,
        "goals": 2,
        "assists": 1,
        "minutes": 868,
        "rating": 6.69,
        "shots": 5,
        "shotsOnTarget": 2,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 8,
        "keyPasses": 10,
        "xG": 0.85,
        "xA": 0.71
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 13,
        "goals": 0,
        "assists": 3,
        "minutes": 1106,
        "rating": 7.02,
        "shots": 4,
        "shotsOnTarget": 2,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 6,
        "keyPasses": 10,
        "xG": 0.6,
        "xA": 1.14
      }
    ],
    "transfers": [
      {
        "from": "Sevilla",
        "to": "FC Barcelona",
        "fee": 50000000,
        "year": null
      },
      {
        "from": "Bordeaux",
        "to": "Sevilla",
        "fee": 35000000,
        "year": null
      },
      {
        "from": "FC Girondins de Bordeaux 2",
        "to": "Bordeaux",
        "fee": null,
        "year": null
      },
      {
        "from": "Bordeaux U19",
        "to": "FC Girondins de Bordeaux 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr8": {
    "id": "fr8",
    "name": "Ibrahima KONATÉ",
    "sofascoreId": 826215,
    "sofascoreSlug": "ibrahima-konate",
    "photo": "https://img.sofascore.com/api/v1/player/826215/image",
    "position": "D",
    "team": "Liverpool FC",
    "country": "France",
    "jerseyNumber": "5",
    "seasons": [
      {
        "tournament": "Premier League",
        "season": "25/26",
        "apps": 36,
        "goals": 1,
        "assists": 0,
        "minutes": 3100,
        "rating": 7.06,
        "shots": 12,
        "shotsOnTarget": 4,
        "yellowCards": 7,
        "redCards": 0,
        "dribbles": 5,
        "keyPasses": 8,
        "xG": 1.21,
        "xA": 0.98
      },
      {
        "tournament": "Premier League",
        "season": "24/25",
        "apps": 30,
        "goals": 1,
        "assists": 2,
        "minutes": 2565,
        "rating": 7.08,
        "shots": 19,
        "shotsOnTarget": 4,
        "yellowCards": 5,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 10,
        "xG": 1.77,
        "xA": 0.93
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 3,
        "goals": 0,
        "assists": 0,
        "minutes": 270,
        "rating": 7.37,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 1,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 10,
        "goals": 1,
        "assists": 0,
        "minutes": 871,
        "rating": 6.99,
        "shots": 9,
        "shotsOnTarget": 2,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 0,
        "xG": 0.97,
        "xA": 0.2
      },
      {
        "tournament": "UEFA Europa League",
        "season": "23/24",
        "apps": 7,
        "goals": 0,
        "assists": 0,
        "minutes": 503,
        "rating": 7.14,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 4,
        "keyPasses": 1,
        "xG": null,
        "xA": 0.22
      },
      {
        "tournament": "UEFA Europa League",
        "season": "18/19",
        "apps": 3,
        "goals": 1,
        "assists": 0,
        "minutes": 270,
        "rating": 7.2,
        "shots": 1,
        "shotsOnTarget": 1,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Bundesliga",
        "season": "20/21",
        "apps": 8,
        "goals": 1,
        "assists": 0,
        "minutes": 695,
        "rating": 6.68,
        "shots": 4,
        "shotsOnTarget": 2,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 8,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "RB Leipzig",
        "to": "Liverpool FC",
        "fee": 40000000,
        "year": null
      },
      {
        "from": "Sochaux",
        "to": "RB Leipzig",
        "fee": null,
        "year": null
      },
      {
        "from": "FC Sochaux 2",
        "to": "Sochaux",
        "fee": null,
        "year": null
      },
      {
        "from": "Sochaux U19",
        "to": "FC Sochaux 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr4": {
    "id": "fr4",
    "name": "William SALIBA",
    "sofascoreId": 941168,
    "sofascoreSlug": "william-saliba",
    "photo": "https://img.sofascore.com/api/v1/player/941168/image",
    "position": "D",
    "team": "Arsenal",
    "country": "France",
    "jerseyNumber": "2",
    "seasons": [
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 12,
        "goals": 0,
        "assists": 0,
        "minutes": 1110,
        "rating": 6.84,
        "shots": 3,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 6,
        "keyPasses": 0,
        "xG": 0.38,
        "xA": 0.2
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 11,
        "goals": 0,
        "assists": 0,
        "minutes": 990,
        "rating": 6.93,
        "shots": 2,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 0,
        "xG": 0.33,
        "xA": 0.14
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 3,
        "goals": 0,
        "assists": 0,
        "minutes": 270,
        "rating": 7.13,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 1,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Premier League",
        "season": "25/26",
        "apps": 30,
        "goals": 1,
        "assists": 0,
        "minutes": 2615,
        "rating": 7.02,
        "shots": 5,
        "shotsOnTarget": 1,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 7,
        "keyPasses": 10,
        "xG": 0.86,
        "xA": 1.42
      },
      {
        "tournament": "Premier League",
        "season": "24/25",
        "apps": 35,
        "goals": 2,
        "assists": 0,
        "minutes": 3041,
        "rating": 7.04,
        "shots": 6,
        "shotsOnTarget": 3,
        "yellowCards": 2,
        "redCards": 1,
        "dribbles": 12,
        "keyPasses": 7,
        "xG": 2.28,
        "xA": 1.29
      },
      {
        "tournament": "UEFA Europa League",
        "season": "22/23",
        "apps": 4,
        "goals": 1,
        "assists": 0,
        "minutes": 291,
        "rating": 6.88,
        "shots": 1,
        "shotsOnTarget": 1,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 1,
        "xG": 0.32,
        "xA": 0.04
      },
      {
        "tournament": "UEFA Europa League",
        "season": "21/22",
        "apps": 6,
        "goals": 0,
        "assists": 0,
        "minutes": 540,
        "rating": 6.97,
        "shots": 2,
        "shotsOnTarget": 1,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 2,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Ligue 1",
        "season": "21/22",
        "apps": 36,
        "goals": 0,
        "assists": 0,
        "minutes": 3240,
        "rating": 7.06,
        "shots": 17,
        "shotsOnTarget": 4,
        "yellowCards": 5,
        "redCards": 0,
        "dribbles": 31,
        "keyPasses": 6,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "Olympique de Marseille",
        "to": "Arsenal",
        "fee": null,
        "year": null
      },
      {
        "from": "Arsenal",
        "to": "Olympique de Marseille",
        "fee": null,
        "year": null
      },
      {
        "from": "Nice",
        "to": "Arsenal",
        "fee": null,
        "year": null
      },
      {
        "from": "Arsenal",
        "to": "Nice",
        "fee": null,
        "year": null
      },
      {
        "from": "Saint-Étienne",
        "to": "Arsenal",
        "fee": null,
        "year": null
      },
      {
        "from": "Arsenal",
        "to": "Saint-Étienne",
        "fee": null,
        "year": null
      },
      {
        "from": "Saint-Étienne",
        "to": "Arsenal",
        "fee": 30000000,
        "year": null
      },
      {
        "from": "AS Saint-Étienne 2",
        "to": "Saint-Étienne",
        "fee": null,
        "year": null
      },
      {
        "from": "Saint-Étienne U19",
        "to": "AS Saint-Étienne 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr7": {
    "id": "fr7",
    "name": "Theo HERNÁNDEZ",
    "sofascoreId": 788027,
    "sofascoreSlug": "theo-hernandez",
    "photo": "https://img.sofascore.com/api/v1/player/788027/image",
    "position": "D",
    "team": "Al-Hilal",
    "country": "France",
    "jerseyNumber": "19",
    "seasons": [
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 3,
        "goals": 0,
        "assists": 1,
        "minutes": 270,
        "rating": 7.3,
        "shots": 2,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 9,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2022",
        "apps": 2,
        "goals": 0,
        "assists": 2,
        "minutes": 180,
        "rating": 7.35,
        "shots": 2,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 2,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Serie A",
        "season": "24/25",
        "apps": 30,
        "goals": 4,
        "assists": 3,
        "minutes": 2696,
        "rating": 7.2,
        "shots": 44,
        "shotsOnTarget": 17,
        "yellowCards": 4,
        "redCards": 1,
        "dribbles": 24,
        "keyPasses": 47,
        "xG": 2.66,
        "xA": 4.07
      },
      {
        "tournament": "Serie A",
        "season": "23/24",
        "apps": 31,
        "goals": 5,
        "assists": 4,
        "minutes": 2795,
        "rating": 7.17,
        "shots": 57,
        "shotsOnTarget": 17,
        "yellowCards": 11,
        "redCards": 1,
        "dribbles": 37,
        "keyPasses": 45,
        "xG": 4.94,
        "xA": 4.57
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 10,
        "goals": 0,
        "assists": 0,
        "minutes": 861,
        "rating": 6.86,
        "shots": 17,
        "shotsOnTarget": 2,
        "yellowCards": 2,
        "redCards": 1,
        "dribbles": 5,
        "keyPasses": 12,
        "xG": 1.15,
        "xA": 0.7
      },
      {
        "tournament": "UEFA Champions League",
        "season": "23/24",
        "apps": 6,
        "goals": 0,
        "assists": 1,
        "minutes": 540,
        "rating": 7.15,
        "shots": 9,
        "shotsOnTarget": 2,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 4,
        "keyPasses": 9,
        "xG": 0.76,
        "xA": 0.64
      },
      {
        "tournament": "UEFA Europa League",
        "season": "23/24",
        "apps": 6,
        "goals": 0,
        "assists": 3,
        "minutes": 540,
        "rating": 7.45,
        "shots": 7,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 12,
        "keyPasses": 12,
        "xG": 0.18,
        "xA": 1.82
      },
      {
        "tournament": "UEFA Europa League",
        "season": "20/21",
        "apps": 6,
        "goals": 1,
        "assists": 2,
        "minutes": 551,
        "rating": 6.8,
        "shots": 8,
        "shotsOnTarget": 2,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 14,
        "keyPasses": 4,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "AC Milan",
        "to": "Al-Hilal",
        "fee": 25000000,
        "year": null
      },
      {
        "from": "Real Madrid",
        "to": "AC Milan",
        "fee": 22800000,
        "year": null
      },
      {
        "from": "Real Sociedad",
        "to": "Real Madrid",
        "fee": null,
        "year": null
      },
      {
        "from": "Real Madrid",
        "to": "Real Sociedad",
        "fee": null,
        "year": null
      },
      {
        "from": "Atlético Madrid",
        "to": "Real Madrid",
        "fee": 24000000,
        "year": null
      },
      {
        "from": "Deportivo Alavés",
        "to": "Atlético Madrid",
        "fee": null,
        "year": null
      },
      {
        "from": "Atlético Madrid",
        "to": "Deportivo Alavés",
        "fee": null,
        "year": null
      },
      {
        "from": "Atlético Madrileño",
        "to": "Atlético Madrid",
        "fee": null,
        "year": null
      },
      {
        "from": "Atlético Madrid U19",
        "to": "Atlético Madrileño",
        "fee": null,
        "year": null
      },
      {
        "from": null,
        "to": "Atlético Madrileño",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr9": {
    "id": "fr9",
    "name": "Lucas HERNÁNDEZ",
    "sofascoreId": 352370,
    "sofascoreSlug": "lucas-hernandez",
    "photo": "https://img.sofascore.com/api/v1/player/352370/image",
    "position": "D",
    "team": "Paris Saint-Germain",
    "country": "France",
    "jerseyNumber": "21",
    "seasons": [
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 0,
        "goals": 0,
        "assists": 0,
        "minutes": 243,
        "rating": 6.6,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 1,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.03
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 1,
        "goals": 0,
        "assists": 0,
        "minutes": 119,
        "rating": 6.62,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": 0.01
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 1,
        "goals": 0,
        "assists": 0,
        "minutes": 90,
        "rating": 6.7,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2022",
        "apps": 3,
        "goals": 0,
        "assists": 0,
        "minutes": 260,
        "rating": 7.1,
        "shots": 2,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 3,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Ligue 1",
        "season": "25/26",
        "apps": 20,
        "goals": 0,
        "assists": 3,
        "minutes": 1751,
        "rating": 7.04,
        "shots": 11,
        "shotsOnTarget": 3,
        "yellowCards": 4,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 15,
        "xG": 0.52,
        "xA": 0.75
      },
      {
        "tournament": "Ligue 1",
        "season": "24/25",
        "apps": 10,
        "goals": 0,
        "assists": 0,
        "minutes": 875,
        "rating": 6.83,
        "shots": 3,
        "shotsOnTarget": 0,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 1,
        "xG": 0.04,
        "xA": 0.18
      },
      {
        "tournament": "Bundesliga",
        "season": "22/23",
        "apps": 6,
        "goals": 0,
        "assists": 0,
        "minutes": 479,
        "rating": 6.87,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 1,
        "xG": null,
        "xA": 0.12
      },
      {
        "tournament": "Bundesliga",
        "season": "21/22",
        "apps": 25,
        "goals": 0,
        "assists": 1,
        "minutes": 2039,
        "rating": 7.01,
        "shots": 4,
        "shotsOnTarget": 1,
        "yellowCards": 7,
        "redCards": 0,
        "dribbles": 17,
        "keyPasses": 9,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "FC Bayern München",
        "to": "Paris Saint-Germain",
        "fee": 45000000,
        "year": null
      },
      {
        "from": "Atlético Madrid",
        "to": "FC Bayern München",
        "fee": 80000000,
        "year": null
      },
      {
        "from": "Atlético Madrileño",
        "to": "Atlético Madrid",
        "fee": null,
        "year": null
      },
      {
        "from": "Atlético Madrid U19",
        "to": "Atlético Madrileño",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr11": {
    "id": "fr11",
    "name": "Maxence LACROIX",
    "sofascoreId": 879674,
    "sofascoreSlug": "maxence-lacroix",
    "photo": "https://img.sofascore.com/api/v1/player/879674/image",
    "position": "D",
    "team": "Crystal Palace",
    "country": "France",
    "jerseyNumber": "5",
    "seasons": [
      {
        "tournament": "Premier League",
        "season": "25/26",
        "apps": 35,
        "goals": 1,
        "assists": 2,
        "minutes": 3087,
        "rating": 6.89,
        "shots": 24,
        "shotsOnTarget": 7,
        "yellowCards": 4,
        "redCards": 1,
        "dribbles": 7,
        "keyPasses": 7,
        "xG": 2.38,
        "xA": 0.89
      },
      {
        "tournament": "Premier League",
        "season": "24/25",
        "apps": 35,
        "goals": 1,
        "assists": 1,
        "minutes": 3118,
        "rating": 7.04,
        "shots": 30,
        "shotsOnTarget": 6,
        "yellowCards": 5,
        "redCards": 0,
        "dribbles": 8,
        "keyPasses": 8,
        "xG": 3.46,
        "xA": 1.05
      },
      {
        "tournament": "Bundesliga",
        "season": "23/24",
        "apps": 27,
        "goals": 4,
        "assists": 1,
        "minutes": 2364,
        "rating": 6.93,
        "shots": 12,
        "shotsOnTarget": 8,
        "yellowCards": 3,
        "redCards": 3,
        "dribbles": 7,
        "keyPasses": 8,
        "xG": 0.82,
        "xA": 1.35
      },
      {
        "tournament": "Bundesliga",
        "season": "22/23",
        "apps": 18,
        "goals": 1,
        "assists": 0,
        "minutes": 1627,
        "rating": 6.85,
        "shots": 4,
        "shotsOnTarget": 1,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 7,
        "keyPasses": 3,
        "xG": 0.5,
        "xA": 0.25
      },
      {
        "tournament": "UEFA Champions League",
        "season": "21/22",
        "apps": 6,
        "goals": 0,
        "assists": 0,
        "minutes": 540,
        "rating": 6.82,
        "shots": 2,
        "shotsOnTarget": 0,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 1,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "VfL Wolfsburg",
        "to": "Crystal Palace",
        "fee": 18000000,
        "year": null
      },
      {
        "from": "Sochaux",
        "to": "VfL Wolfsburg",
        "fee": 5000000,
        "year": null
      },
      {
        "from": "Sochaux U19",
        "to": "Sochaux",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr19": {
    "id": "fr19",
    "name": "Manu KONÉ",
    "sofascoreId": 974087,
    "sofascoreSlug": "manu-kone",
    "photo": "https://img.sofascore.com/api/v1/player/974087/image",
    "position": "M",
    "team": "AS Roma",
    "country": "France",
    "jerseyNumber": "17",
    "seasons": [
      {
        "tournament": "Serie A",
        "season": "25/26",
        "apps": 28,
        "goals": 2,
        "assists": 3,
        "minutes": 2459,
        "rating": 7.02,
        "shots": 21,
        "shotsOnTarget": 5,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 29,
        "keyPasses": 25,
        "xG": 2.11,
        "xA": 2.51
      },
      {
        "tournament": "Serie A",
        "season": "24/25",
        "apps": 31,
        "goals": 2,
        "assists": 1,
        "minutes": 2582,
        "rating": 6.91,
        "shots": 34,
        "shotsOnTarget": 9,
        "yellowCards": 6,
        "redCards": 0,
        "dribbles": 30,
        "keyPasses": 21,
        "xG": 3.34,
        "xA": 1.56
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 4,
        "goals": 0,
        "assists": 0,
        "minutes": 350,
        "rating": 7.3,
        "shots": 5,
        "shotsOnTarget": 1,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 5,
        "keyPasses": 7,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Europa League",
        "season": "25/26",
        "apps": 5,
        "goals": 0,
        "assists": 0,
        "minutes": 266,
        "rating": 6.57,
        "shots": 6,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 6,
        "keyPasses": 2,
        "xG": 0.23,
        "xA": 0.41
      },
      {
        "tournament": "UEFA Europa League",
        "season": "24/25",
        "apps": 9,
        "goals": 0,
        "assists": 2,
        "minutes": 768,
        "rating": 7.09,
        "shots": 5,
        "shotsOnTarget": 0,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 13,
        "keyPasses": 11,
        "xG": 0.2,
        "xA": 0.74
      },
      {
        "tournament": "Bundesliga",
        "season": "23/24",
        "apps": 18,
        "goals": 1,
        "assists": 0,
        "minutes": 1571,
        "rating": 6.84,
        "shots": 24,
        "shotsOnTarget": 8,
        "yellowCards": 4,
        "redCards": 1,
        "dribbles": 37,
        "keyPasses": 24,
        "xG": 1.15,
        "xA": 0.75
      },
      {
        "tournament": "Bundesliga",
        "season": "22/23",
        "apps": 30,
        "goals": 1,
        "assists": 1,
        "minutes": 2619,
        "rating": 6.86,
        "shots": 26,
        "shotsOnTarget": 14,
        "yellowCards": 12,
        "redCards": 0,
        "dribbles": 57,
        "keyPasses": 20,
        "xG": 1.2,
        "xA": 1.31
      },
      {
        "tournament": "Ligue 1",
        "season": "19/20",
        "apps": 11,
        "goals": 0,
        "assists": 0,
        "minutes": 875,
        "rating": 6.58,
        "shots": 9,
        "shotsOnTarget": 2,
        "yellowCards": 3,
        "redCards": 1,
        "dribbles": 11,
        "keyPasses": 5,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "Borussia M'gladbach",
        "to": "AS Roma",
        "fee": 18000000,
        "year": null
      },
      {
        "from": "Toulouse",
        "to": "Borussia M'gladbach",
        "fee": null,
        "year": null
      },
      {
        "from": "Borussia M'gladbach",
        "to": "Toulouse",
        "fee": null,
        "year": null
      },
      {
        "from": "Toulouse",
        "to": "Borussia M'gladbach",
        "fee": 9000000,
        "year": null
      },
      {
        "from": "Toulouse 2",
        "to": "Toulouse",
        "fee": null,
        "year": null
      },
      {
        "from": "Toulouse U19",
        "to": "Toulouse 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr15": {
    "id": "fr15",
    "name": "Aurélien TCHOUAMÉNI",
    "sofascoreId": 859025,
    "sofascoreSlug": "aurelien-tchouameni",
    "photo": "https://img.sofascore.com/api/v1/player/859025/image",
    "position": "M",
    "team": "Real Madrid",
    "country": "France",
    "jerseyNumber": "14",
    "seasons": [
      {
        "tournament": "LaLiga",
        "season": "25/26",
        "apps": 31,
        "goals": 1,
        "assists": 0,
        "minutes": 2622,
        "rating": 7.23,
        "shots": 45,
        "shotsOnTarget": 7,
        "yellowCards": 8,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 25,
        "xG": 2.66,
        "xA": 2.95
      },
      {
        "tournament": "LaLiga",
        "season": "24/25",
        "apps": 31,
        "goals": 0,
        "assists": 0,
        "minutes": 2692,
        "rating": 7.1,
        "shots": 19,
        "shotsOnTarget": 3,
        "yellowCards": 5,
        "redCards": 0,
        "dribbles": 10,
        "keyPasses": 5,
        "xG": 1.65,
        "xA": 0.91
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 2,
        "goals": 0,
        "assists": 1,
        "minutes": 158,
        "rating": 8,
        "shots": 1,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 1,
        "dribbles": 0,
        "keyPasses": 6,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2022",
        "apps": 2,
        "goals": 0,
        "assists": 0,
        "minutes": 237,
        "rating": 7.03,
        "shots": 1,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Copa del Rey",
        "season": "25/26",
        "apps": 0,
        "goals": 0,
        "assists": 1,
        "minutes": 13,
        "rating": null,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Copa del Rey",
        "season": "24/25",
        "apps": 5,
        "goals": 2,
        "assists": 1,
        "minutes": 540,
        "rating": null,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 13,
        "goals": 1,
        "assists": 1,
        "minutes": 1125,
        "rating": 7.12,
        "shots": 16,
        "shotsOnTarget": 5,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 6,
        "keyPasses": 10,
        "xG": 0.89,
        "xA": 0.81
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 10,
        "goals": 0,
        "assists": 0,
        "minutes": 805,
        "rating": 7.11,
        "shots": 7,
        "shotsOnTarget": 2,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 4,
        "keyPasses": 6,
        "xG": 0.24,
        "xA": 0.4
      }
    ],
    "transfers": [
      {
        "from": "AS Monaco",
        "to": "Real Madrid",
        "fee": 80000000,
        "year": null
      },
      {
        "from": "Bordeaux",
        "to": "AS Monaco",
        "fee": 18000000,
        "year": null
      },
      {
        "from": "FC Girondins de Bordeaux 2",
        "to": "Bordeaux",
        "fee": null,
        "year": null
      },
      {
        "from": "Bordeaux U19",
        "to": "FC Girondins de Bordeaux 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr17": {
    "id": "fr17",
    "name": "Adrien RABIOT",
    "sofascoreId": 250737,
    "sofascoreSlug": "adrien-rabiot",
    "photo": "https://img.sofascore.com/api/v1/player/250737/image",
    "position": "M",
    "team": "AC Milan",
    "country": "France",
    "jerseyNumber": "12",
    "seasons": [
      {
        "tournament": "Serie A",
        "season": "25/26",
        "apps": 28,
        "goals": 6,
        "assists": 4,
        "minutes": 2550,
        "rating": 7.23,
        "shots": 46,
        "shotsOnTarget": 12,
        "yellowCards": 4,
        "redCards": 1,
        "dribbles": 20,
        "keyPasses": 27,
        "xG": 4.28,
        "xA": 3.41
      },
      {
        "tournament": "Serie A",
        "season": "23/24",
        "apps": 30,
        "goals": 5,
        "assists": 3,
        "minutes": 2651,
        "rating": 7.23,
        "shots": 38,
        "shotsOnTarget": 17,
        "yellowCards": 8,
        "redCards": 0,
        "dribbles": 28,
        "keyPasses": 26,
        "xG": 3.48,
        "xA": 3.96
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 1,
        "goals": 1,
        "assists": 0,
        "minutes": 104,
        "rating": 7.13,
        "shots": 3,
        "shotsOnTarget": 1,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 4,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2022",
        "apps": 6,
        "goals": 1,
        "assists": 1,
        "minutes": 567,
        "rating": 7.21,
        "shots": 10,
        "shotsOnTarget": 5,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 5,
        "keyPasses": 2,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Ligue 1",
        "season": "25/26",
        "apps": 1,
        "goals": 0,
        "assists": 0,
        "minutes": 90,
        "rating": 6.5,
        "shots": 1,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 4,
        "xG": 0.04,
        "xA": 0.51
      },
      {
        "tournament": "Ligue 1",
        "season": "24/25",
        "apps": 27,
        "goals": 9,
        "assists": 4,
        "minutes": 2483,
        "rating": 7.41,
        "shots": 48,
        "shotsOnTarget": 24,
        "yellowCards": 4,
        "redCards": 0,
        "dribbles": 26,
        "keyPasses": 28,
        "xG": 7.26,
        "xA": 3.8
      },
      {
        "tournament": "UEFA Europa League",
        "season": "22/23",
        "apps": 8,
        "goals": 1,
        "assists": 1,
        "minutes": 750,
        "rating": 7.01,
        "shots": 11,
        "shotsOnTarget": 4,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 17,
        "keyPasses": 9,
        "xG": 1.58,
        "xA": 1.43
      },
      {
        "tournament": "UEFA Champions League",
        "season": "22/23",
        "apps": 5,
        "goals": 2,
        "assists": 0,
        "minutes": 447,
        "rating": 7.28,
        "shots": 4,
        "shotsOnTarget": 2,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 4,
        "keyPasses": 4,
        "xG": 0.59,
        "xA": 0.34
      }
    ],
    "transfers": [
      {
        "from": "Olympique de Marseille",
        "to": "AC Milan",
        "fee": 7000000,
        "year": null
      },
      {
        "from": "No team",
        "to": "Olympique de Marseille",
        "fee": null,
        "year": null
      },
      {
        "from": "Juventus",
        "to": "No team",
        "fee": null,
        "year": null
      },
      {
        "from": "Paris Saint-Germain",
        "to": "Juventus",
        "fee": null,
        "year": null
      },
      {
        "from": "Toulouse",
        "to": "Paris Saint-Germain",
        "fee": null,
        "year": null
      },
      {
        "from": "Paris Saint-Germain",
        "to": "Toulouse",
        "fee": null,
        "year": null
      },
      {
        "from": "Paris Saint-Germain U19",
        "to": "Paris Saint-Germain",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr20": {
    "id": "fr20",
    "name": "Warren ZAÏRE-EMERY",
    "sofascoreId": 1142672,
    "sofascoreSlug": "warren-zaire-emery",
    "photo": "https://img.sofascore.com/api/v1/player/1142672/image",
    "position": "M",
    "team": "Paris Saint-Germain",
    "country": "France",
    "jerseyNumber": "33",
    "seasons": [
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 15,
        "goals": 0,
        "assists": 1,
        "minutes": 1343,
        "rating": 6.52,
        "shots": 14,
        "shotsOnTarget": 2,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 9,
        "keyPasses": 22,
        "xG": 1.01,
        "xA": 1.49
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 6,
        "goals": 1,
        "assists": 0,
        "minutes": 602,
        "rating": 6.83,
        "shots": 8,
        "shotsOnTarget": 1,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 6,
        "keyPasses": 10,
        "xG": 1.22,
        "xA": 0.42
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 1,
        "goals": 0,
        "assists": 0,
        "minutes": 100,
        "rating": 6.95,
        "shots": 1,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Ligue 1",
        "season": "25/26",
        "apps": 27,
        "goals": 3,
        "assists": 4,
        "minutes": 2453,
        "rating": 7,
        "shots": 19,
        "shotsOnTarget": 7,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 30,
        "keyPasses": 42,
        "xG": 1.22,
        "xA": 3.5
      },
      {
        "tournament": "Ligue 1",
        "season": "24/25",
        "apps": 23,
        "goals": 1,
        "assists": 2,
        "minutes": 2052,
        "rating": 6.99,
        "shots": 17,
        "shotsOnTarget": 7,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 20,
        "keyPasses": 18,
        "xG": 1.67,
        "xA": 1.43
      }
    ],
    "transfers": [
      {
        "from": "Paris Saint-Germain U19",
        "to": "Paris Saint-Germain",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr25": {
    "id": "fr25",
    "name": "Ousmane DEMBÉLÉ",
    "sofascoreId": 818244,
    "sofascoreSlug": "ousmane-dembele",
    "photo": "https://img.sofascore.com/api/v1/player/818244/image",
    "position": "F",
    "team": "Paris Saint-Germain",
    "country": "France",
    "jerseyNumber": "10",
    "seasons": [
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 11,
        "goals": 8,
        "assists": 2,
        "minutes": 827,
        "rating": 7.25,
        "shots": 34,
        "shotsOnTarget": 14,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 5,
        "keyPasses": 21,
        "xG": 6.55,
        "xA": 1.86
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 13,
        "goals": 8,
        "assists": 6,
        "minutes": 1162,
        "rating": 7.63,
        "shots": 64,
        "shotsOnTarget": 23,
        "yellowCards": 0,
        "redCards": 1,
        "dribbles": 24,
        "keyPasses": 39,
        "xG": 8.28,
        "xA": 2.76
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 0,
        "goals": 0,
        "assists": 0,
        "minutes": 36,
        "rating": 6.3,
        "shots": 2,
        "shotsOnTarget": 1,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2022",
        "apps": 1,
        "goals": 1,
        "assists": 0,
        "minutes": 116,
        "rating": 6.8,
        "shots": 3,
        "shotsOnTarget": 2,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 3,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Ligue 1",
        "season": "25/26",
        "apps": 11,
        "goals": 10,
        "assists": 7,
        "minutes": 1062,
        "rating": 7.42,
        "shots": 45,
        "shotsOnTarget": 18,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 24,
        "keyPasses": 41,
        "xG": 6.6,
        "xA": 4.5
      },
      {
        "tournament": "Ligue 1",
        "season": "24/25",
        "apps": 20,
        "goals": 21,
        "assists": 6,
        "minutes": 1736,
        "rating": 7.75,
        "shots": 97,
        "shotsOnTarget": 51,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 42,
        "keyPasses": 63,
        "xG": 16.61,
        "xA": 7.18
      },
      {
        "tournament": "LaLiga",
        "season": "22/23",
        "apps": 16,
        "goals": 5,
        "assists": 7,
        "minutes": 1415,
        "rating": 7.18,
        "shots": 49,
        "shotsOnTarget": 17,
        "yellowCards": 4,
        "redCards": 0,
        "dribbles": 52,
        "keyPasses": 42,
        "xG": 3.92,
        "xA": 5.04
      },
      {
        "tournament": "LaLiga",
        "season": "21/22",
        "apps": 15,
        "goals": 1,
        "assists": 13,
        "minutes": 1411,
        "rating": 7.53,
        "shots": 46,
        "shotsOnTarget": 8,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 59,
        "keyPasses": 46,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "FC Barcelona",
        "to": "Paris Saint-Germain",
        "fee": 50000000,
        "year": null
      },
      {
        "from": "Borussia Dortmund",
        "to": "FC Barcelona",
        "fee": 148000000,
        "year": null
      },
      {
        "from": "Stade Rennais",
        "to": "Borussia Dortmund",
        "fee": 35000000,
        "year": null
      },
      {
        "from": "Stade Rennais FC 2",
        "to": "Stade Rennais",
        "fee": null,
        "year": null
      },
      {
        "from": "Stade Rennais U19",
        "to": "Stade Rennais FC 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr28": {
    "id": "fr28",
    "name": "Marcus THURAM",
    "sofascoreId": 791702,
    "sofascoreSlug": "marcus-thuram",
    "photo": "https://img.sofascore.com/api/v1/player/791702/image",
    "position": "F",
    "team": "Inter",
    "country": "France",
    "jerseyNumber": "9",
    "seasons": [
      {
        "tournament": "Serie A",
        "season": "24/25",
        "apps": 27,
        "goals": 14,
        "assists": 4,
        "minutes": 2298,
        "rating": 7.3,
        "shots": 65,
        "shotsOnTarget": 27,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 24,
        "keyPasses": 40,
        "xG": 10.06,
        "xA": 4.08
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 1,
        "goals": 0,
        "assists": 0,
        "minutes": 70,
        "rating": 7.1,
        "shots": 7,
        "shotsOnTarget": 3,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 6,
        "goals": 2,
        "assists": 1,
        "minutes": 577,
        "rating": 7,
        "shots": 30,
        "shotsOnTarget": 6,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 7,
        "keyPasses": 12,
        "xG": 2.35,
        "xA": 1.39
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 11,
        "goals": 4,
        "assists": 1,
        "minutes": 952,
        "rating": 7.01,
        "shots": 22,
        "shotsOnTarget": 8,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 12,
        "keyPasses": 11,
        "xG": 3.42,
        "xA": 1.19
      },
      {
        "tournament": "Bundesliga",
        "season": "22/23",
        "apps": 28,
        "goals": 13,
        "assists": 6,
        "minutes": 2516,
        "rating": 7.02,
        "shots": 92,
        "shotsOnTarget": 44,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 41,
        "keyPasses": 30,
        "xG": 16.55,
        "xA": 3.12
      },
      {
        "tournament": "Bundesliga",
        "season": "21/22",
        "apps": 8,
        "goals": 3,
        "assists": 0,
        "minutes": 890,
        "rating": 6.77,
        "shots": 31,
        "shotsOnTarget": 10,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 23,
        "keyPasses": 13,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Europa League",
        "season": "19/20",
        "apps": 6,
        "goals": 2,
        "assists": 0,
        "minutes": 520,
        "rating": 6.9,
        "shots": 11,
        "shotsOnTarget": 6,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 10,
        "keyPasses": 6,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "Borussia M'gladbach",
        "to": "Inter",
        "fee": null,
        "year": null
      },
      {
        "from": "Guingamp",
        "to": "Borussia M'gladbach",
        "fee": 9000000,
        "year": null
      },
      {
        "from": "Sochaux",
        "to": "Guingamp",
        "fee": 600000,
        "year": null
      },
      {
        "from": "FC Sochaux 2",
        "to": "Sochaux",
        "fee": null,
        "year": null
      },
      {
        "from": "Sochaux U19",
        "to": "FC Sochaux 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr24": {
    "id": "fr24",
    "name": "Kylian MBAPPÉ",
    "sofascoreId": 826643,
    "sofascoreSlug": "kylian-mbappe",
    "photo": "https://img.sofascore.com/api/v1/player/826643/image",
    "position": "F",
    "team": "Real Madrid",
    "country": "France",
    "jerseyNumber": "10",
    "seasons": [
      {
        "tournament": "LaLiga",
        "season": "25/26",
        "apps": 29,
        "goals": 25,
        "assists": 5,
        "minutes": 2604,
        "rating": 7.56,
        "shots": 146,
        "shotsOnTarget": 63,
        "yellowCards": 4,
        "redCards": 0,
        "dribbles": 78,
        "keyPasses": 65,
        "xG": 23.95,
        "xA": 6.2
      },
      {
        "tournament": "LaLiga",
        "season": "24/25",
        "apps": 34,
        "goals": 31,
        "assists": 3,
        "minutes": 2915,
        "rating": 7.7,
        "shots": 161,
        "shotsOnTarget": 85,
        "yellowCards": 3,
        "redCards": 1,
        "dribbles": 83,
        "keyPasses": 52,
        "xG": 25.93,
        "xA": 6.59
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 4,
        "goals": 5,
        "assists": 3,
        "minutes": 353,
        "rating": 8.43,
        "shots": 29,
        "shotsOnTarget": 12,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 12,
        "keyPasses": 11,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2022",
        "apps": 5,
        "goals": 5,
        "assists": 2,
        "minutes": 465,
        "rating": 7.5,
        "shots": 19,
        "shotsOnTarget": 11,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 14,
        "keyPasses": 5,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Copa del Rey",
        "season": "25/26",
        "apps": 1,
        "goals": 2,
        "assists": 0,
        "minutes": 90,
        "rating": null,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Copa del Rey",
        "season": "24/25",
        "apps": 1,
        "goals": 2,
        "assists": 0,
        "minutes": 234,
        "rating": null,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 0,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 10,
        "goals": 15,
        "assists": 1,
        "minutes": 912,
        "rating": 8.05,
        "shots": 56,
        "shotsOnTarget": 30,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 20,
        "keyPasses": 31,
        "xG": 10.79,
        "xA": 2.5
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 13,
        "goals": 7,
        "assists": 1,
        "minutes": 1132,
        "rating": 7.28,
        "shots": 51,
        "shotsOnTarget": 27,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 24,
        "keyPasses": 15,
        "xG": 9.19,
        "xA": 1.62
      }
    ],
    "transfers": [
      {
        "from": "Paris Saint-Germain",
        "to": "Real Madrid",
        "fee": null,
        "year": null
      },
      {
        "from": "AS Monaco",
        "to": "Paris Saint-Germain",
        "fee": 180000000,
        "year": null
      },
      {
        "from": "Paris Saint-Germain",
        "to": "AS Monaco",
        "fee": null,
        "year": null
      },
      {
        "from": "AS Monaco",
        "to": "Paris Saint-Germain",
        "fee": null,
        "year": null
      },
      {
        "from": "AS Monaco U19",
        "to": "AS Monaco",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr26": {
    "id": "fr26",
    "name": "Michael OLISE",
    "sofascoreId": 978838,
    "sofascoreSlug": "michael-olise",
    "photo": "https://img.sofascore.com/api/v1/player/978838/image",
    "position": "M",
    "team": "FC Bayern München",
    "country": "France",
    "jerseyNumber": "17",
    "seasons": [
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 5,
        "goals": 2,
        "assists": 0,
        "minutes": 427,
        "rating": 8.34,
        "shots": 13,
        "shotsOnTarget": 5,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 22,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Bundesliga",
        "season": "25/26",
        "apps": 23,
        "goals": 15,
        "assists": 19,
        "minutes": 2317,
        "rating": 7.87,
        "shots": 101,
        "shotsOnTarget": 50,
        "yellowCards": 8,
        "redCards": 0,
        "dribbles": 65,
        "keyPasses": 81,
        "xG": 11.46,
        "xA": 17.23
      },
      {
        "tournament": "Bundesliga",
        "season": "24/25",
        "apps": 28,
        "goals": 12,
        "assists": 15,
        "minutes": 2346,
        "rating": 7.91,
        "shots": 86,
        "shotsOnTarget": 36,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 72,
        "keyPasses": 93,
        "xG": 9.75,
        "xA": 12.51
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 12,
        "goals": 5,
        "assists": 6,
        "minutes": 1081,
        "rating": 7.61,
        "shots": 45,
        "shotsOnTarget": 19,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 45,
        "keyPasses": 34,
        "xG": 4.74,
        "xA": 4.92
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 13,
        "goals": 5,
        "assists": 2,
        "minutes": 1033,
        "rating": 7.62,
        "shots": 41,
        "shotsOnTarget": 13,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 25,
        "keyPasses": 22,
        "xG": 5.07,
        "xA": 4.96
      },
      {
        "tournament": "Premier League",
        "season": "23/24",
        "apps": 14,
        "goals": 10,
        "assists": 6,
        "minutes": 1277,
        "rating": 7.74,
        "shots": 57,
        "shotsOnTarget": 21,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 40,
        "keyPasses": 36,
        "xG": 5.51,
        "xA": 4.99
      },
      {
        "tournament": "Premier League",
        "season": "22/23",
        "apps": 31,
        "goals": 2,
        "assists": 11,
        "minutes": 2762,
        "rating": 7.13,
        "shots": 51,
        "shotsOnTarget": 14,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 54,
        "keyPasses": 72,
        "xG": 2.95,
        "xA": 6.44
      }
    ],
    "transfers": [
      {
        "from": "Crystal Palace",
        "to": "FC Bayern München",
        "fee": 53000000,
        "year": null
      },
      {
        "from": "Reading",
        "to": "Crystal Palace",
        "fee": 9300000,
        "year": null
      },
      {
        "from": "Reading U18",
        "to": "Reading",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr27": {
    "id": "fr27",
    "name": "Bradley BARCOLA",
    "sofascoreId": 996952,
    "sofascoreSlug": "barcola-bradley",
    "photo": "https://img.sofascore.com/api/v1/player/996952/image",
    "position": "F",
    "team": "Paris Saint-Germain",
    "country": "France",
    "jerseyNumber": "29",
    "seasons": [
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 12,
        "goals": 2,
        "assists": 4,
        "minutes": 989,
        "rating": 6.8,
        "shots": 25,
        "shotsOnTarget": 11,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 18,
        "keyPasses": 25,
        "xG": 4.05,
        "xA": 1.91
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 14,
        "goals": 3,
        "assists": 4,
        "minutes": 1096,
        "rating": 7.13,
        "shots": 31,
        "shotsOnTarget": 13,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 29,
        "keyPasses": 25,
        "xG": 6.09,
        "xA": 3.31
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 3,
        "goals": 1,
        "assists": 1,
        "minutes": 217,
        "rating": 7.05,
        "shots": 5,
        "shotsOnTarget": 2,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 5,
        "keyPasses": 5,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Ligue 1",
        "season": "25/26",
        "apps": 21,
        "goals": 11,
        "assists": 1,
        "minutes": 1750,
        "rating": 7.21,
        "shots": 67,
        "shotsOnTarget": 31,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 36,
        "keyPasses": 38,
        "xG": 10.83,
        "xA": 4.5
      },
      {
        "tournament": "Ligue 1",
        "season": "24/25",
        "apps": 27,
        "goals": 14,
        "assists": 10,
        "minutes": 2192,
        "rating": 7.25,
        "shots": 74,
        "shotsOnTarget": 39,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 34,
        "keyPasses": 51,
        "xG": 13.58,
        "xA": 5.93
      },
      {
        "tournament": "UEFA Europa League",
        "season": "21/22",
        "apps": 0,
        "goals": 0,
        "assists": 1,
        "minutes": 27,
        "rating": 7.1,
        "shots": 1,
        "shotsOnTarget": 0,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 2,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "Olympique Lyonnais",
        "to": "Paris Saint-Germain",
        "fee": 45000000,
        "year": null
      },
      {
        "from": "Olympique Lyonnais 2",
        "to": "Olympique Lyonnais",
        "fee": null,
        "year": null
      },
      {
        "from": "Olympique Lyon U19",
        "to": "Olympique Lyonnais 2",
        "fee": null,
        "year": null
      },
      {
        "from": "Olympique Lyon U19",
        "to": "Olympique Lyonnais 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr32": {
    "id": "fr32",
    "name": "Désiré DOUÉ",
    "sofascoreId": 1154605,
    "sofascoreSlug": "desire-doue",
    "photo": "https://img.sofascore.com/api/v1/player/1154605/image",
    "position": "F",
    "team": "Paris Saint-Germain",
    "country": "France",
    "jerseyNumber": "14",
    "seasons": [
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 9,
        "goals": 5,
        "assists": 4,
        "minutes": 871,
        "rating": 7.49,
        "shots": 28,
        "shotsOnTarget": 11,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 24,
        "keyPasses": 32,
        "xG": 2.09,
        "xA": 3.13
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 8,
        "goals": 5,
        "assists": 3,
        "minutes": 741,
        "rating": 7.37,
        "shots": 32,
        "shotsOnTarget": 17,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 22,
        "keyPasses": 17,
        "xG": 2.71,
        "xA": 2.72
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 1,
        "goals": 0,
        "assists": 0,
        "minutes": 45,
        "rating": 6.6,
        "shots": 3,
        "shotsOnTarget": 1,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 1,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Ligue 1",
        "season": "25/26",
        "apps": 16,
        "goals": 7,
        "assists": 4,
        "minutes": 1356,
        "rating": 7.13,
        "shots": 55,
        "shotsOnTarget": 19,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 32,
        "keyPasses": 29,
        "xG": 7.92,
        "xA": 3.04
      },
      {
        "tournament": "Ligue 1",
        "season": "24/25",
        "apps": 18,
        "goals": 6,
        "assists": 6,
        "minutes": 1734,
        "rating": 7.32,
        "shots": 55,
        "shotsOnTarget": 20,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 57,
        "keyPasses": 55,
        "xG": 5.14,
        "xA": 5.67
      },
      {
        "tournament": "UEFA Europa League",
        "season": "23/24",
        "apps": 4,
        "goals": 0,
        "assists": 0,
        "minutes": 347,
        "rating": 7.03,
        "shots": 16,
        "shotsOnTarget": 4,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 11,
        "keyPasses": 8,
        "xG": 0.86,
        "xA": 0.33
      },
      {
        "tournament": "UEFA Europa League",
        "season": "22/23",
        "apps": 1,
        "goals": 1,
        "assists": 0,
        "minutes": 213,
        "rating": 6.66,
        "shots": 8,
        "shotsOnTarget": 3,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 11,
        "keyPasses": 1,
        "xG": 0.6,
        "xA": 0.08
      }
    ],
    "transfers": []
  },
  "fr31": {
    "id": "fr31",
    "name": "Jean-Philippe MATETA",
    "sofascoreId": 848276,
    "sofascoreSlug": "jean-philippe-mateta",
    "photo": "https://img.sofascore.com/api/v1/player/848276/image",
    "position": "F",
    "team": "Crystal Palace",
    "country": "France",
    "jerseyNumber": "14",
    "seasons": [
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 2,
        "goals": 2,
        "assists": 0,
        "minutes": 179,
        "rating": 6.97,
        "shots": 7,
        "shotsOnTarget": 3,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 3,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Premier League",
        "season": "25/26",
        "apps": 25,
        "goals": 12,
        "assists": 0,
        "minutes": 2222,
        "rating": 6.75,
        "shots": 63,
        "shotsOnTarget": 32,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 14,
        "keyPasses": 9,
        "xG": 14.51,
        "xA": 1.31
      },
      {
        "tournament": "Premier League",
        "season": "24/25",
        "apps": 33,
        "goals": 14,
        "assists": 2,
        "minutes": 2654,
        "rating": 6.92,
        "shots": 70,
        "shotsOnTarget": 33,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 20,
        "keyPasses": 29,
        "xG": 13.53,
        "xA": 2.27
      },
      {
        "tournament": "Bundesliga",
        "season": "20/21",
        "apps": 12,
        "goals": 7,
        "assists": 1,
        "minutes": 1001,
        "rating": 6.75,
        "shots": 29,
        "shotsOnTarget": 14,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 12,
        "keyPasses": 13,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Bundesliga",
        "season": "19/20",
        "apps": 12,
        "goals": 3,
        "assists": 1,
        "minutes": 1056,
        "rating": 6.62,
        "shots": 35,
        "shotsOnTarget": 12,
        "yellowCards": 0,
        "redCards": 1,
        "dribbles": 17,
        "keyPasses": 6,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Ligue 1",
        "season": "16/17",
        "apps": 1,
        "goals": 0,
        "assists": 0,
        "minutes": 86,
        "rating": 6.55,
        "shots": 0,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 0,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "1. FSV Mainz 05",
        "to": "Crystal Palace",
        "fee": 11000000,
        "year": null
      },
      {
        "from": "Crystal Palace",
        "to": "1. FSV Mainz 05",
        "fee": null,
        "year": null
      },
      {
        "from": "1. FSV Mainz 05",
        "to": "Crystal Palace",
        "fee": null,
        "year": null
      },
      {
        "from": "Olympique Lyonnais",
        "to": "1. FSV Mainz 05",
        "fee": 8000000,
        "year": null
      },
      {
        "from": "Le Havre",
        "to": "Olympique Lyonnais",
        "fee": null,
        "year": null
      },
      {
        "from": "Olympique Lyonnais",
        "to": "Le Havre",
        "fee": null,
        "year": null
      },
      {
        "from": "Châteauroux",
        "to": "Olympique Lyonnais",
        "fee": 4099999,
        "year": null
      },
      {
        "from": "LB Châteauroux B",
        "to": "Châteauroux",
        "fee": null,
        "year": null
      },
      {
        "from": "Chateauroux U19",
        "to": "LB Châteauroux B",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr22": {
    "id": "fr22",
    "name": "Rayan CHERKI",
    "sofascoreId": 979128,
    "sofascoreSlug": "cherki-rayan",
    "photo": "https://img.sofascore.com/api/v1/player/979128/image",
    "position": "M",
    "team": "Manchester City",
    "country": "France",
    "jerseyNumber": "10",
    "seasons": [
      {
        "tournament": "Premier League",
        "season": "25/26",
        "apps": 19,
        "goals": 4,
        "assists": 12,
        "minutes": 1794,
        "rating": 7.21,
        "shots": 55,
        "shotsOnTarget": 13,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 51,
        "keyPasses": 61,
        "xG": 4.13,
        "xA": 8.65
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 1,
        "goals": 0,
        "assists": 0,
        "minutes": 96,
        "rating": 7.3,
        "shots": 4,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 7,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 4,
        "goals": 3,
        "assists": 0,
        "minutes": 399,
        "rating": 7.49,
        "shots": 15,
        "shotsOnTarget": 9,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 10,
        "keyPasses": 7,
        "xG": 1.08,
        "xA": 1.68
      },
      {
        "tournament": "UEFA Champions League",
        "season": "19/20",
        "apps": 0,
        "goals": 0,
        "assists": 0,
        "minutes": 32,
        "rating": 6.5,
        "shots": 1,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 1,
        "keyPasses": 1,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "Ligue 1",
        "season": "24/25",
        "apps": 22,
        "goals": 8,
        "assists": 11,
        "minutes": 2053,
        "rating": 7.6,
        "shots": 45,
        "shotsOnTarget": 19,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 48,
        "keyPasses": 75,
        "xG": 5.01,
        "xA": 11.73
      },
      {
        "tournament": "Ligue 1",
        "season": "23/24",
        "apps": 19,
        "goals": 1,
        "assists": 6,
        "minutes": 1717,
        "rating": 7.11,
        "shots": 57,
        "shotsOnTarget": 17,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 81,
        "keyPasses": 42,
        "xG": 5.17,
        "xA": 5.53
      },
      {
        "tournament": "UEFA Europa League",
        "season": "24/25",
        "apps": 11,
        "goals": 4,
        "assists": 8,
        "minutes": 919,
        "rating": 8,
        "shots": 25,
        "shotsOnTarget": 12,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 34,
        "keyPasses": 46,
        "xG": 2.23,
        "xA": 5.85
      },
      {
        "tournament": "UEFA Europa League",
        "season": "21/22",
        "apps": 3,
        "goals": 2,
        "assists": 1,
        "minutes": 287,
        "rating": 7.9,
        "shots": 7,
        "shotsOnTarget": 4,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 9,
        "keyPasses": 10,
        "xG": null,
        "xA": null
      }
    ],
    "transfers": [
      {
        "from": "Olympique Lyonnais",
        "to": "Manchester City",
        "fee": 36500000,
        "year": null
      },
      {
        "from": "Olympique Lyonnais 2",
        "to": "Olympique Lyonnais",
        "fee": null,
        "year": null
      },
      {
        "from": "Olympique Lyon U19",
        "to": "Olympique Lyonnais 2",
        "fee": null,
        "year": null
      }
    ]
  },
  "fr23": {
    "id": "fr23",
    "name": "Maghnes AKLIOUCHE",
    "sofascoreId": 1130939,
    "sofascoreSlug": "maghnes-akliouche",
    "photo": "https://img.sofascore.com/api/v1/player/1130939/image",
    "position": "M",
    "team": "AS Monaco",
    "country": "France",
    "jerseyNumber": "11",
    "seasons": [
      {
        "tournament": "Ligue 1",
        "season": "25/26",
        "apps": 28,
        "goals": 6,
        "assists": 6,
        "minutes": 2410,
        "rating": 7.05,
        "shots": 48,
        "shotsOnTarget": 19,
        "yellowCards": 3,
        "redCards": 0,
        "dribbles": 26,
        "keyPasses": 44,
        "xG": 7.22,
        "xA": 5.37
      },
      {
        "tournament": "Ligue 1",
        "season": "24/25",
        "apps": 27,
        "goals": 5,
        "assists": 10,
        "minutes": 2409,
        "rating": 7.31,
        "shots": 62,
        "shotsOnTarget": 19,
        "yellowCards": 2,
        "redCards": 0,
        "dribbles": 50,
        "keyPasses": 51,
        "xG": 9.26,
        "xA": 7.83
      },
      {
        "tournament": "World Cup Qual. UEFA",
        "season": "2026",
        "apps": 1,
        "goals": 1,
        "assists": 1,
        "minutes": 131,
        "rating": 7,
        "shots": 2,
        "shotsOnTarget": 2,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 2,
        "keyPasses": 4,
        "xG": null,
        "xA": null
      },
      {
        "tournament": "UEFA Champions League",
        "season": "25/26",
        "apps": 10,
        "goals": 1,
        "assists": 3,
        "minutes": 835,
        "rating": 6.85,
        "shots": 26,
        "shotsOnTarget": 11,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 20,
        "keyPasses": 19,
        "xG": 3.26,
        "xA": 1.81
      },
      {
        "tournament": "UEFA Champions League",
        "season": "24/25",
        "apps": 10,
        "goals": 2,
        "assists": 2,
        "minutes": 807,
        "rating": 7.07,
        "shots": 19,
        "shotsOnTarget": 8,
        "yellowCards": 1,
        "redCards": 0,
        "dribbles": 13,
        "keyPasses": 13,
        "xG": 1.48,
        "xA": 1.35
      },
      {
        "tournament": "UEFA Europa League",
        "season": "22/23",
        "apps": 0,
        "goals": 0,
        "assists": 0,
        "minutes": 45,
        "rating": 6.8,
        "shots": 1,
        "shotsOnTarget": 0,
        "yellowCards": 0,
        "redCards": 0,
        "dribbles": 3,
        "keyPasses": 2,
        "xG": 0.06,
        "xA": 0.14
      }
    ],
    "transfers": [
      {
        "from": "AS Monaco U21",
        "to": "AS Monaco",
        "fee": null,
        "year": null
      }
    ]
  }
};
